### ISSUE TITLE
As a Data owner/Data manager I want to have a central source of information for the JCDP project (eg data protocols, ToR etc) ..so that alI the agreed information is all in one place

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#11]
original id#8
Agree with the principal of a central place. But detail of what's on it (versus sitting on showcase with expert group etc) to be determined  
would like these items to be agreed upfront and circulated - being in a central place can come later
eg ICES working group have a sharepoint for this kind of data

**Comment by cmspinto** [comment]
Sharepoint site?

**Comment by NikkiTaylorJNCC** [comment]
Function fulfilled by the JCDP hub
