### ISSUE TITLE
As a Data owner/Data manager I want to be able to upload optional fields (more than just the core fields) ..so that I can retain key peripheral data in the dataset for use_agree data standard

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#15]
original id#12
"Additional fields" have to be in the standard - can't be outside of those defined in the standard 
We have to have a standard with agreed core and agreed additional fields

**Comment by cmspinto** [comment]
There are no control in additional fields!
It is not advisable and how would you explain that to the users?
How would you be able to merge distinct formats?

**Comment by neil-ices-dk** [comment]
@LynnHeeley and @kellymacleod suggest to reject (have labelled as such)

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed;
Will be included with the data standard, and relevant elements for development picked up through that route.
