### ISSUE TITLE
As a data users I want to clearly understand potential biases in methodologies so that I can account for these in my analyses

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#154]
e.g. perception bias and/or availability bias addressed? Or none of those, etc.

**Comment by NikiClear** [comment]
Provided by metadata and within the dataset (methodologies field). 
Also the data collection document being developed covers bias in distance/transect sampling.

Could be closed

**Comment by NikkiTaylorJNCC** [comment]
Covered by metadata - complete
