### ISSUE TITLE
As a Data owner/Data manager I want to be able to remove all/some of my data as needed ..so that I can ensure the integrity of the data_discuss

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#16]
original id#13
More a role for a coordinator - can liaise with ICES to convey an issue 
clarify that I have the ability to highlight unhappiness to a coordinator and be able to remove my data from the database

**Comment by cmspinto** [comment]
Same as issue #22

**Comment by neil-ices-dk** [comment]
duplicate of #22 suggest to reject @LynnHeeley and @kellymacleod

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed;
Duplicated in other tickets and included in MVP or Phase 2.

**Comment by LynnHeeley** [comment]
include in comms/data standard - coordinator role
