### ISSUE TITLE
As a Data user I want to be able to select a standard region to investigate so that I have options to easily extract data from the system / analyse data

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#162]
Split from #104  to separate geospatial selections

Standard regions will come from a predetermined list (to be determined, but likely OSPAR and/or MSFD)

@neil-ices-dk 'in the ICES bag'?

**Comment by neil-ices-dk** [comment]
Bagged 🛄

**Comment by LynnHeeley** [comment]
duplicate of #62
