### ISSUE TITLE
As a Data Owner/Manager I want to be able to log into the system securely and view the data (restricted and unrestricted) that I have uploaded

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#167]
added in sub-group 2 Thurs morning session

**Comment by LynnHeeley** [comment]
overlap with #33 @neil-ices-dk is this 'in the ICES bag' as #33 is labelled as such? would the owner be able to view the data they have uploaded or is this also referring to a basic summary?

**Comment by neil-ices-dk** [comment]
@LynnHeeley yes i think this is different - viewing the detail records, rather than a meta-summary of what is uploaded; we have this in place in other systems but i will defer to @cmspinto to confirm this is in the bag or not?

**Comment by LynnHeeley** [comment]
Steering Group Meeting 26th March agreed that owners could just download their own data to view the detail. reject and close
