### ISSUE TITLE
As a data owner I want to be able to streamline the metadata requirement to suit my specific need in order to keep the burden to a minimum

### ISSUE THREAD

**Issue by NikkiTaylorJNCC** [ices-tools-dev/cetaceans#168]
In terms of a provider profile for 'standard' or ;general metadata, but allowing for more focused metadata where required.

**Comment by GMDuncan** [comment]
Ability to create a metadata record that is applicable to the level that the owner wants. E.g.

- One per seurvey

- One per a suite of surveys

**Comment by LynnHeeley** [comment]
admin to set up a template for data providers to use
