### ISSUE TITLE
As a Data owner/Data manager I want to be able to track requests to access data....so that I can monitor use of my data to understand frequency of use, and who by_basic stats

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#17]
original id#14
First part aligns with an objective around tracking use - if its restricted then tracking is built in 
For open data, have to consider "citation" 
Can automate an alert to usesrs on download. 
What is meant by" paid outside the system".
NGOs need to know how it's being used - but some uses they are happy for data to be open and would like a mechanism to allow that.

**Comment by cmspinto** [comment]
Needs clarification

**Comment by neil-ices-dk** [comment]
@LynnHeeley see #45 for suggested approach; onus would be on data provider, however we could provide basic stats on requests i.e. number and time period

**Comment by LynnHeeley** [comment]
@neil-ices-dk is that with google analytics /similar or a manual process?

**Comment by neil-ices-dk** [comment]
> https://github.com/ices-tools-dev/cetaceans/issues/19#issuecomment-756659080

see above @LynnHeeley, bespoke but automated

**Comment by LynnHeeley** [comment]
@neil-ices-dk are you envisaging this to be on the data provider page (ie not on  the public 'dashboard' of use #126 )

**Comment by LynnHeeley** [comment]
Public dashboard – 2 record counters (total database AND per data provider)
•	Simple table view – one table needs to be able to choose data provider
Count of inactive restricted download, count of activated restricted downloads, count of open access downloads
•	Total KM of effort
•	Total time - Years of data
•	Total number of surveys
•	Total number of sightings

**Comment by kellymacleod** [comment]
@LynnHeeley @neil-ices-dk total km of effort is calculated from waypoints and speed

**Comment by neil-ices-dk** [comment]
> 
> 
> • Total time - Years of data
>

discontinuous years (Count) of data **or** span of years of data (min/max)?
