### ISSUE TITLE
As a data provider/user I want to understand the definition of terms e.g. 'dataset' or 'survey' so I am clear on how to classify the data

### ISSUE THREAD

**Issue by NikkiTaylorJNCC** [ices-tools-dev/cetaceans#171]
Create a glossary in the data standard?

**Comment by neil-ices-dk** [comment]
@kellymacleod agree this is part of data standard definition; not really a big deal/ticket

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed;
Will be included with the data standard, and relevant elements for development picked up through that route.
