### ISSUE TITLE
As a data owner/manager I want to provide a specific citation for end-users, so that my data are attributed correctly when used.

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#172]
Data provider (dataset specific?) citation statement to be provided alongside the data.

Two levels of citation in ICES - basic 'minimum' citation, and a wider one including ref to all relevant orgs. 
DOI addition also - helps with data tracking.

**Comment by NikkiTaylorJNCC** [comment]
Complete - JCDP citation provided and guidance on how to cite/acknowledge in the supplementary data submission, access and use guidance document
