### ISSUE TITLE
As a Data/Web Manager I want to be able to use some data validation tools (within the system) to ensure that errors in the data are minimised, and to meet data standards that have been set.

### ISSUE THREAD

**Issue by pcrjoana** [ices-tools-dev/cetaceans#174]

**Comment by LynnHeeley** [comment]
@pcrjoana is this after individual dataset upload (eg the whole JCDP database) or as part of the validation at upload please?

**Comment by pcrjoana** [comment]
@LynnHeeley it's part of the validation at upload. I think we included so that the basic features of the system were covered in the user stories. :-)

**Comment by LynnHeeley** [comment]
should include human readable feedback on any errors present
