### ISSUE TITLE
TEMPLATE: As a data owner/manager, I want to be able to create a standard metadata record for my dataset so that users have the context they need to use the data correctly

### ISSUE THREAD

**Issue by GMDuncan** [ices-tools-dev/cetaceans#181]

**Comment by LynnHeeley** [comment]
manual creation with a guiding standard

**Comment by neil-ices-dk** [comment]
duplicated by #168

**Comment by neil-ices-dk** [comment]
still need this for sending out to data pilots - 10th November - will use as 'draft'

**Comment by PeriklisICES** [comment]
I tried to address some questions and changed a few sections to make them more precise. I think overall it is a good document and has a good level of detail. However, we need to communicate that running into difficulties is expected and they should contact us.
[JCDP.Metadata.Standard_User.guide_v0.1_pp.docx](https://github.com/ices-tools-dev/cetaceans/files/7476878/JCDP.Metadata.Standard_User.guide_v0.1_pp.docx)

**Comment by NikiClear** [comment]
Thanks for the feedback so far. Version 1 of Metadata guidance for the December workshop - please let me know if any further changes are needed before sending to the workshop participants. We can refine this with feedback from the users before gen @NikkiTaylorJNCC @PeriklisICES @GMDuncan @LynnHeeley 
[JCDP.Metadata.Standard_User.guide_v1.docx](https://github.com/ices-tools-dev/cetaceans/files/7514112/JCDP.Metadata.Standard_User.guide_v1.docx)

**Comment by NikkiTaylorJNCC** [comment]
@NikiClear layout is well structured and clear. I would be fairly happy for this to go out to the pilot users and gain more feedback as we use the guide to input metadata. If all the pilot users are set up with user accounts in Geonetwork, I might get them going on this with an email today, and follow up on the data entry once I get the green light from @cmspinto and @pcrjoana

**Comment by NikiClear** [comment]
Thanks @NikkiTaylorJNCC. Geonetwork accounts have been set up for the pilot users and they have their account details. 
- ORCA
- HWDT
- HiDef
(I will be uploading pilot data from SCANS and Pelagis)
