### ISSUE TITLE
As a Data owner/Data manager I want to get a download alert when my data is being downloaded (includes use information) ..so that I can track use

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#19]
original id#17

**Comment by cmspinto** [comment]
we don't keep information about the user that downloads the data.

**Comment by neil-ices-dk** [comment]
see #45 for restricted data, but otherwise we would not provide this functionality for open data; 

@kellymacleod suggest a dashboard on the portal

![image](https://user-images.githubusercontent.com/23527005/104000653-dda20e80-519e-11eb-8c4c-0333c0b397e2.png)

**Comment by LynnHeeley** [comment]
#126

**Comment by LynnHeeley** [comment]
download alert out of scope see #126 for dashboard suggestion and description. closed as out of scope.
