### ISSUE TITLE
As a Data/Web manager I want to ensure that the data and portal is archived regularly ..so that I can ensure previous data versions are stored correctly

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#208]

**Comment by NikkiTaylorJNCC** [comment]
@neil-ices-dk does ICES have data archiving as part and parcel of the system? I'm trying to establish what happens within ICES, and what is required outside eg DASSH. 
There is a chance only open access data will be archived through DASSH, depending on the outcome of a discussion I started with them today. 
Can I also confirm is ICES submit anything to e.g. OBIS etc., as we need to ensure there is no duplication issue.

Aim is to archive annually most likely, in line with the annual submission timeframe.

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC the ICES Data and Information Group is working on an overall 'Data Preservation Plan' for the organisation, but that is not in place yet. In the meantime, i think we do do this but i would need you to explain what is meant by archiving in this context. Requirement 7 and 9 of the Core Trust Seal accreditation is about Digital Object Management (see our response https://www.coretrustseal.org/wp-content/uploads/2021/03/International-Council-for-the-Exploration-of-the-Sea.pdf) 

ICES is a partner in EMD Biology, and therefore connected to OBIS in that way. We agree on a dataset collection basis what should be available to be harvested by EMD Bio. We have not made any plans, or flagged cetaceans as yet, as this would be something for the ICES JCDP working group to discuss.

**Comment by GMDuncan** [comment]
Sounds good -in which case regarding DASSH @NikkiTaylorJNCC you would just need to decide whether to get records into OBIS via ICES or DASSH (ICES seems more direct? Up to you however!), and if going with ICES, just let DASSH know not to pass on to EurOBIS.

(Still good for them to pass to the NBN however!)

**Comment by NikkiTaylorJNCC** [comment]
Fab, ok - I think we will need to map all this out so everyone is clear on the flow of data and who is doing what.  In terms of defining archiving - my understanding is to ensure the long term availability of the data but with the ICES data centre and sharing of the data with DASSH/OBIS NBN etc. I think we are well covered.
