### ISSUE TITLE
PUBLISHING WORKFLOW: As a JCDP Admin I want to be able to publish other JCDP data owner's metadata so that I can ensure the quality of metadata being published

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#213]
Admin the only one that can publish - not the metadata owner themselves.

**Comment by LynnHeeley** [comment]
Needs a mechanism for notification that there is metadata waiting to be published @GMDuncan how does this work in EModnet workflow?

**Comment by GMDuncan** [comment]
@LynnHeeley @NikkiTaylorJNCC 
Do we want a formal review workflow, where JNCC (or similar project admin) would approve the metadata record (or reject). And do we want the admin to receive an email when an email is on a workflow?

This may add extra complexity for the user to start the workflow with the appropriate button but should be learned relatively quickly.

**Comment by NikkiTaylorJNCC** [comment]
@GMDuncan @LynnHeeley I'm not 100% clear on what you mean by 'formal review workflow' - but essentially yes, I think we need a metadata 'approval' stage for publishing by a central admin (whoever that may be - assume JCDP coordinator initially) for appropriate QA, and an alert for submissions waiting for approval would be very helpful to ensure publishing is sorted quickly. Failing that it may be a weekly task to check and publish metadata submissions....?

**Comment by GMDuncan** [comment]
Thanks @NikkiTaylorJNCC  yes that sounds like a proper workflow including email alerts to me!

**Comment by neil-ices-dk** [comment]
> @PeriklisICES to setup simple workflow and check the automated email works

@PeriklisICES can you confirm if this is in place and issue can be closed - thanks

**Comment by PeriklisICES** [comment]
The workflow is in place but the automatic email does not work. There seems to be a bug in the current version of Geonetwork in this functionality. Users need to manually send an email to inform if there is a status update in their records. I am expecting this to be magically fixed when I update Geonetwork to a newer version.

**Comment by neil-ices-dk** [comment]
closing and follow-up action in #242
