### ISSUE TITLE
Meta data clarifications

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#220]
@GMDuncan to have a chat with Periklis on the planned issues before October Sprints where this will be dealt with

[Oct.2](https://github.com/ices-tools-dev/cetaceans/milestone/4) 
[Oct.1](https://github.com/ices-tools-dev/cetaceans/milestone/3)

**Comment by GMDuncan** [comment]
@PeriklisICES I'm busy with EMODnet Technical Working group this week, but fairly free next week if you have any suitable times to chat?

**Comment by PeriklisICES** [comment]
@GMDuncan Yes next week is fine. Any day is fine except Friday.

**Comment by neil-ices-dk** [comment]
@PeriklisICES please update with the info you had on email

**Comment by PeriklisICES** [comment]
I have created a group for the project called JCDP under which all the records and users will sit. All the records published under this group will be available through the subportal: https://gis.ices.dk/geonetwork/JCDP
I have also created a user Admin for the group with the following credentials:

User: JCDP_user_admin

This user can create more users under the JCDP group and assign privileges (See Descriptions below).

I also created a Template based on the Emodnet Habitat one, but it still needs some work.
To view the Template you need to log in with any user belonging to the group:
https://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/f642956b-ff7a-4f9f-8e86-0f463f25016e


1.	User Administrator Profile
The User Administrator is the administrator of his/her own group with the following privileges:
•	Full rights on creating new users within the own group
•	Rights to change users profiles within the own group
•	Full rights on creating/editing/ deleting new/old data within the own group
•	Rights on reviewing metadata content within the own group and authorizing its publication

2.	Content Reviewer Profile
The content reviewer is the only person together with the Admin allowed to give final clearance on the metadata publication on the Intranet and/or on the Internet:
•	Rights on reviewing metadata content within the own group and authorizing its publication

3.	Editor Profile
The editor works on metadata with following privileges:
•	Full rights on creating/editing/ deleting new/old data within the own group

**Comment by neil-ices-dk** [comment]
thanks @PeriklisICES in the next Oct.1 sprint we will put this information onto the relevant user stories issues. Great progress ahead of schedule!
