### ISSUE TITLE
data providers for initial testing of format

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#222]
we need the Excel template to be established prior to this. #12 

- [ ] SCANS (Excel)
- [ ] HIDEF
- [ ] ORCA
- [ ] HWDT
- [ ] Mathieu Autier (IFREMER)

**Comment by NikkiTaylorJNCC** [comment]
@cmspinto @pcrjoana @neil-ices-dk @PeriklisICES  - Is it looking likely that we will be able to get the pilot data volunteers entering data/metadata this week as hoped? If you can please flag with Niki and I here once the system is ready to go...
