### ISSUE TITLE
Establish Database according to Data Standard/Vocab on ICES SQL Server

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#224]

**Comment by NikkiTaylorJNCC** [comment]
@pcrjoana is it possible to get the up to date version of the data standard, so I can circulate to those willing to provide pilot data?

**Comment by neil-ices-dk** [comment]
Database is created in SQL06; awaiting pilot data

**Comment by neil-ices-dk** [comment]
database established - screening of data now possible

**Comment by neil-ices-dk** [comment]
- screening, sessions and import to DB work
Roles for users:
- Sharepoint logins are in principle personal, this means that we would need to use EMDO codes to link logins so that all people from the same organisation can see the submissions
- this would be a feature in the cetaceans management interface (admin); this would be a manual process where admins have to assign the EDMO's to the users. 
@cmspinto to implement this feature

**Comment by neil-ices-dk** [comment]
NikkiC is sending over an Excel with 2, 000 records of effort that can be also used here to test the database.
