### ISSUE TITLE
Edits to landing page

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#228]
[landing page](https://www.ices.dk/data/data-portals/Pages/Cetaceans.aspx)
to feed to neil for inclusion

**Comment by NikkiTaylorJNCC** [comment]
@neil-ices-dk apologies, updated the wrong ticket. Below info also added to #225

a few edits to the text on the landing page. Suspect I will need to run this by the SG as well in my next email update, so may be some suggestions from them also:

Cetaceans (whales, dolphins and porpoises) data to understand their abundance and distribution.
This portal assembles at-sea effort-related data collected via ship-based or aerial methods, collated under the Joint Cetacean Database Programme (JCDP).

The JCDP aims to streamline the process of accessing and utilising these data by collating the existing and forthcoming cetacean evidence base into a single resource. These data have a wide range of applications and have the potential to support analyses at a range of spatial and temporal scales. For more information, visit the JCDP hub (see links)

[Could we rename the link to ‘JCDP hub’]

**Comment by neil-ices-dk** [comment]
> a few edits to the text on the landing page. Suspect I will need to run this by the SG as well in my next email update, so may be some suggestions from them also:

done, should we add a link to WGMME?

**Comment by NikkiTaylorJNCC** [comment]
> > a few edits to the text on the landing page. Suspect I will need to run this by the SG as well in my next email update, so may be some suggestions from them also:
> 
> done, should we add a link to WGMME?

@neil-ices-dk  I think we can add this at a later date, once we have the Working Group and associations agreed.

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to add excel template to landing page from
http://cetaceans.ices.dk/upload/Cetaceans_data_template.xlsm 
when this is done, will ask Carlos to remove from app

**Comment by neil-ices-dk** [comment]
done. note that the format is wrapped in a .zip as per standard practice - allowing a generic URL regardless of the actual version of the template that is current

![image](https://user-images.githubusercontent.com/23527005/143455114-ba6b03e1-e1ed-423e-a85b-13be44b00a7c.png)
