### ISSUE TITLE
As a Data owner/Data manager I want to share my data and receive a summary of how it's being used ..so that I can use this information to support data sharing and the importance of the portal

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#23]
original id#20
would require a form/pre-filled box for anonymous users to fill in before download
links to a big ticket?

**Comment by cmspinto** [comment]
We don't track "how it's being used" because we allow data download of open access data without user login.

**Comment by neil-ices-dk** [comment]
@kellymacleod suggest to reject this

**Comment by LynnHeeley** [comment]
Steering Group Jan2021 agreed this is for the coordinator role

**Comment by LynnHeeley** [comment]
Outside of the system: Was covered under discussions of “tracking solutions” proposed by ICES. But acknowledged that the Coordinator and Showcase plays a role sharing “uses” of the JCDP.
