### ISSUE TITLE
ShipCode (platforms) setup mini workshop

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#231]

**Comment by NikkiTaylorJNCC** [comment]
Hi @pcrjoana  - just a nudge to let us know the info needed to approach data collectors about setting up any further ship codes.

**Comment by neil-ices-dk** [comment]
[user manual](https://vocab.ices.dk/request/help/RequestsUserGuide.pdf)
to check their [ships/platforms](https://vocab.ices.dk/Request/Login.aspx?ReturnUrl=%2frequest)

**Comment by neil-ices-dk** [comment]
will be referenced in 8th Dec workshop, and can then be detailed further in January follow-up workshop

**Comment by neil-ices-dk** [comment]
Duncan at Marine Discovery has tried contacting through email (@pcrjoana to check accessions)

**Comment by neil-ices-dk** [comment]
@pcrjoana and @NikkiTaylorJNCC to determine if a mini WK is necessary, and a timeline for this

**Comment by neil-ices-dk** [comment]
Joana has already run 1:1 sessions, and this seems more effective, so we will go forward with this approach.
