### ISSUE TITLE
WGJCDP Resolution and group formation

### ISSUE THREAD

**Issue by NikkiTaylorJNCC** [ices-tools-dev/cetaceans#232]
Resolution has been drafted and uploaded to the ICES sharepoint. Comments received and Nikki has updated - awaiting further feedback from ICES in order to finalised and get sign off on the group from SciComm to begin next steps.

**Comment by neil-ices-dk** [comment]
Posted on SCICOM/ACOM for approval;

**Comment by neil-ices-dk** [comment]
Resolution approved 24/11 WGJCDP is born
