### ISSUE TITLE
User profiles and submission ownership

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/cetaceans#235]
What we can do is link that person with an organization (EDMO code).
If another user/person is linked to the same EDMO code they can both manage the submissions from that organization. 
In summary, if a user leave an institution then another user from the same institution can take over the submissions. 

Questions:
a) Can a user submit data and be linked with more than one organization?

b) Is it a problem in some organizations if all the users of that organization can manage the submissions from that organization?

**Comment by neil-ices-dk** [comment]
see #224 decision and feature
