### ISSUE TITLE
8th December - Workshop to do's

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#236]
- Joana preparing walk-through/presentation of data submission setup and process
- @PeriklisICES preparing a walk-through/presentation for the submission setup and process for meta data
- [x]  @NikkiTaylorJNCC to circulate updated Data Standard, meta data guidance and link to published template
- Confirm all those that are attending are also setup in system (logins and EDMO's etc.)
- @NikkiTaylorJNCC to send out message with link to v1.10 of data template once published
- [x] Jon has setup a meeting to talk about data protection (GDPR) 
- [x] form for capturing issue [JCDP quality control](https://forms.office.com/r/rwEym4XPZq)

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC to circulate all materials before the 8th; and we will have a check-in prior to the official start of the meeting @ 10am DK/9am UK time

**Comment by PeriklisICES** [comment]
[JCDP Workshop 2021 metadata.pptx](https://github.com/ices-tools-dev/cetaceans/files/7659882/JCDP.Workshop.2021.metadata.pptx)
@NikkiTaylorJNCC Here is the quick introduction to metadata I have prepared. I am aiming to use around 5-10 minutes for this and then go into a demo using the catalogue and the guidelines document.

**Comment by NikkiTaylorJNCC** [comment]
> [JCDP Workshop 2021 metadata.pptx](https://github.com/ices-tools-dev/cetaceans/files/7659882/JCDP.Workshop.2021.metadata.pptx) @NikkiTaylorJNCC Here is the quick introduction to metadata I have prepared. I am aiming to use around 5-10 minutes for this and then go into a demo using the catalogue and the guidelines document.

Great! Thanks Periklis - I'll save a local copy, but i'll leave you to share your screen on Wed so you have control over presenting.
