### ISSUE TITLE
Change to Identifier Record?

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#239]
1. First to clarify that, in principle, the 'Data access' field in the identifier record refers to the other record types (sampling and effort), and not to the Identifier record itself, which should be considered public meta information
2. If this is agreed, the fields related to data owner/data originator could be simplified (we only need the custodian, the rest can be in the meta data catalgue record)
3. Remove fields 7 and 8 (Data Owner)
4. Rename fields DataOriginator to DataCustodian (to align with metadata) and make mandatory
5. or the other way around if that is easier ;)

![image](https://user-images.githubusercontent.com/23527005/145211097-e9da48b1-6de3-44e2-a85d-54cb252d6193.png)

**Comment by GMDuncan** [comment]
@neil-ices-dk this looks sensible to me. One additional thought on top of those mentioned in meeting.

Removing of Data Owner from the data itself may make conversion into the international standard Darwin-Core (DwC) a little tricker. The "[rightsHolder](https://dwc.tdwg.org/terms/#dcterms:rightsHolder)" DwC field wont be found in the data itself, so would have to be sourced from some joining to metadata.

However this is only an issue if the JCDP group think it's an issue ;) It mainly has impact on distribution of records into OBIS/GBIF or similar systems (and MEDIN by association).

**Comment by neil-ices-dk** [comment]
1. First to clarify that, in principle, the 'Data access' field in the identifier record refers to the other record types (sampling and effort), and not to the Identifier record itself, which should be considered public meta information
2. If this is agreed, the fields related to data owner/data originator could be simplified (we only need the custodian, the rest can be in the meta data catalgue record)
3. Rename fields 7 (DataRightsHolder) - fieldType = varchar
4. Remove field 8 (DataOwnerContact)
5. Rename fields DataOriginator to DataCustodian (to align with ISO metadata) and make mandatory

@pcrjoana to change in Excel template/DATSU
@cmspinto to update database
@NikkiTaylorJNCC change in data standard

**Comment by neil-ices-dk** [comment]
will be part of v2. data template
