### ISSUE TITLE
A single, central place to easily access comprehensive cetacean data for the North East Atlantic

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#24]
original id#21

Overarching objective, not U.S.

**Comment by cmspinto** [comment]
That is the main goal of the development of the cetaceans data portal 👍

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed:
Objective, not user story.

**Comment by LynnHeeley** [comment]
objective not user story
