### ISSUE TITLE
follow-up workshop sessions for data submitters (March)

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#243]
to be raised at the project management meeting 27th Jan.

**Comment by neil-ices-dk** [comment]
Nikki has made two tentative 'drop in surgery' dates (3 March and 18th March) where the idea would be to have submitters drop in and ask specific questions, and keep the formality to a minimum.

**Comment by neil-ices-dk** [comment]
refined idea - to have two half-day sessions (morning preferable) at the proposed dates. @NikkiTaylorJNCC to send out save the dates for the two sessions

**Comment by neil-ices-dk** [comment]
- JNCC to give short recap overview
- submitters with ICES to then go into Q&A and help sessions as needed

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to automate the feedback form to ping accessions@ices.dk and marinemammals@jncc.gov.uk

**Comment by neil-ices-dk** [comment]
> @neil-ices-dk to automate the feedback form to ping [accessions@ices.dk](mailto:accessions@ices.dk) and [marinemammals@jncc.gov.uk](mailto:marinemammals@jncc.gov.uk)

Feedback from now udpated https://forms.office.com/r/rwEym4XPZq 
entering response sends email to marinemammals (JNCC) and Accessions (ICES)

Any further additions to the feedback form?

**Comment by NikkiTaylorJNCC** [comment]
> > @neil-ices-dk to automate the feedback form to ping [accessions@ices.dk](mailto:accessions@ices.dk) and [marinemammals@jncc.gov.uk](mailto:marinemammals@jncc.gov.uk)
> 
> Feedback form now udpated https://forms.office.com/r/rwEym4XPZq entering response sends email to marinemammals (JNCC) and Accessions (ICES)
> 
> Any further additions to the feedback form?

I think that's fine now @neil-ices-dk thanks!

**Comment by neil-ices-dk** [comment]
potentially 5 attendees, Niki to chase up with email along with notification to new template
