### ISSUE TITLE
Publish JCDP data standard

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#245]
to be done based on data template v2.

**Comment by neil-ices-dk** [comment]
awaiting some clarifications on the template/vocab descriptions/field removal
Joana is now making a new version of template - version number for template will be v2.0!

**Comment by pcrjoana** [comment]
> awaiting some clarifications on the template/vocab descriptions/field removal Joana is now making a new version of template - version number for template will be v2.0! to also change data rights holder as optional, custodian as mandatory

This has been implemented.

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC the filed "SurveyTeam" is listed as conditional mandatory. Which is the condition here?

**Comment by NikkiTaylorJNCC** [comment]
> @NikkiTaylorJNCC the filed "SurveyTeam" is listed as conditional mandatory. Which is the condition here? Should it actually be mandatory, since we have a "Not recorded" option?

Yes - should just be mandatory, thanks.

**Comment by pcrjoana** [comment]
> > @NikkiTaylorJNCC the filed "SurveyTeam" is listed as conditional mandatory. Which is the condition here? Should it actually be mandatory, since we have a "Not recorded" option?
> 
> Yes - should just be mandatory, thanks.

It's fixed. I'll send the corrected template to @neil-ices-dk today, but he's on vacation, so it'll probably take a bit of time until it's updated on the website.

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC sorry for the harassment, I'm now doing the data validation, and therefore scrutinizing the conditional mandatory fields. :-)

MinGroupSize and MaxGroupSize are listed as conditional mandatory fields. What are the conditions?

**Comment by neil-ices-dk** [comment]
> I will holding out on sending the template to Neil until I have an answer on this, in case the answer results in changes to the template. :-)

standing by from Hamburg to update v2.? when you are ready ladies.

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to add link to data standard landing page to cetaceans.ices.dk landing page

**Comment by neil-ices-dk** [comment]
linked to JCDP portal
![image](https://user-images.githubusercontent.com/23527005/157872105-57a18a7b-fae5-4fa5-9a1b-7038292a687b.png)
