### ISSUE TITLE
Metadata Guidance from the feedback during the workshop. Could this be checked and commented please? 

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#247]
I've updated the Metadata Guidance from the feedback during the workshop. Could this be checked and commented please? @PeriklisICES @NikkiTaylorJNCC @neil-ices-dk 

[JCDP.Metadata.Standard_User.guide_v2.docx](https://github.com/ices-tools-dev/cetaceans/files/7949537/JCDP.Metadata.Standard_User.guide_v2.docx)

_(I could not find an appropriate issue ticket for this, but happy to move if there is one)_

_Originally posted by @NikiClear in https://github.com/ices-tools-dev/cetaceans/issues/221#issuecomment-1023054667_

**Comment by PeriklisICES** [comment]
Looks good to me. I just added a paragraph on creating a series of records as I think we were asked about it during the workshop.
[JCDP.Metadata.Standard_User.guide_v2_pp.docx](https://github.com/ices-tools-dev/cetaceans/files/7971408/JCDP.Metadata.Standard_User.guide_v2_pp.docx)

**Comment by NikiClear** [comment]
> 

Thanks Periklis, that's perfect. I've made that change and attached the latest version. 
[JCDP.Metadata.Standard_User.guide_v2.01.docx](https://github.com/ices-tools-dev/cetaceans/files/7972225/JCDP.Metadata.Standard_User.guide_v2.01.docx)

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC will the final resting place of this document be the main JCDP website (the JNCC one), and if so should we be providing a link to it from the JCDP data portal?

**Comment by cmspinto** [comment]
Almost all of our actual data is uploaded to the portal now but I just have a few questions about the metadata:
1.	The metadata guidance says that we update the metadata draft with the dataset identifier before we submit the metadata. Is this the accession ID on the submission page and if so where in the metadata does it go?
2.	The guidance also says that we need the metadata identifier when we upload the dataset but I haven't seen anywhere for that to go during the upload process. Have I missed something?
3.	Could we have just one metadata entry for all the years of data on a particular route or it is better to have an individual one for each year? 

Also, as of today I have been getting a new error message when I try to upload the last few datasets. I have tried everything I could think of to solve it but nothing has worked yet: 
 
![image](https://user-images.githubusercontent.com/8705477/160091291-d3ad63fa-d050-4a9f-8374-83528f7e3e81.png)

**Comment by neil-ices-dk** [comment]
Q1: The metadata guidance says that we update the metadata draft with the dataset identifier before we submit the metadata. Is this the accession ID on the submission page and if so where in the metadata does it go?
@PeriklisICES can you take a look and confirm if we meant the accessionID as the 'dataset Identifier'
https://data.jncc.gov.uk/data/1b35ddf6-c469-4bf8-8300-86ec21da1c2d/jcdp-metadata-guidance-v1-0.pdf 
![image](https://user-images.githubusercontent.com/23527005/160092080-a40669ba-743a-4546-91c3-107f935c393f.png)
@NikiClear to update metadata guidance as directed by Periklis

Q2. The guidance also says that we need the metadata identifier when we upload the dataset but I haven't seen anywhere for that to go during the upload process. Have I missed something?

this should be removed from guidance

**Comment by PeriklisICES** [comment]
Q1: I think this goes back to the early discussions where it was decided we want a two way communication between data and metadata. I am not sure if the "dataset identifier" was set. I would hope that @cmspinto or @pcrjoana might know more as they know the upload system. But I think the better question is where in the metadata does it go. I would say it depends on the nature of the identifier. If it is a part of a url then the online resource should be enough. If it is a code that is required to get the file then we would have to use some extra field in the "distribution format" or "transfer options"

Q3: There are instructions in the guidelines for this. It should be handled as a child resource. See section "Creating a series of records" in the document.

**Comment by neil-ices-dk** [comment]
thanks @PeriklisICES ok to avoid a circular discussion, i think we take the decision that the identifier is in fact the accessionID. For the time being, this is a code, although with AIMS we would be able to provide a URL. What is your informed opinion of the best field to store in this in the metadata?

**Comment by PeriklisICES** [comment]
I think an idea that wouldn't complicate things too much would be to use Alternate title for the Accession ID. It is fairly visible and conceptually it is not a huge compromise. EMODnet is doing a similar thing. As of now we have indicated that Alternate title is an ** alternative name of your survey **. So the template would have to change a little bit.

**Comment by PeriklisICES** [comment]
Alternate title is unique for each record.
In the case of multiple surveys they would have to create a parent/child relation. We have described this option in the guidelines. 
They would need one overall record and then child records with different titles/altTitles. Another option would be to just enter all the IDs using commas.

If you think this is not relevant or not practical we will have to find another field in the metadata.
In the "INSPIRE" view other options are: Abstract (using commas), Encoding, Lineage(using commas).
In the extended schema there are some other options like the ones I mention in the previous post.

I have made the alt title field visible in INSPIRE view by default.

**Comment by neil-ices-dk** [comment]
@cmspinto 

### WORKFLOW: 
1 create metadata record
2 upload survey data
3 on upload add metadata record URI ices.geonetwork or ID
4 inventory will link survey data to metadata

For the linking of Metadata (geonetwork) and Survey Data (cetaceans.ices.dk):
- On the data submission page, there should be a mandatory field "Metadata URI" (URL identifier)
- This field would then allow the data to be linked to the metadata record

@pcrjoana to identify existing survey/metadata links, so that Carlos can insert these into the DB

@PeriklisICES, @cmspinto and @neil-ices-dk to think about how we backwards engineer the other way.

**Comment by NikkiTaylorJNCC** [comment]
@NikiClear to update the metadata guidance to reduce the burden of validation on users - full validation will happen in the final review by ICES/JNCC

**Comment by NikiClear** [comment]
@PeriklisICES @pcrjoana @NikkiTaylorJNCC @neil-ices-dk 

Here is the final updated version of the metadata guidance for checking before we re-publish. Could you check the content to make sure it reflects the workflow and makes sense. 

Thanks, 
Niki
[JCDP.Metadata.Standard_User.guide_PubV1.3.docx](https://github.com/ices-tools-dev/cetaceans/files/8738663/JCDP.Metadata.Standard_User.guide_PubV1.3.docx)

**Comment by neil-ices-dk** [comment]
include just the main flagged issues that have come from reviewing the submitted meta records;
@PeriklisICES and @pcrjoana to discuss

**Comment by NikiClear** [comment]
> @PeriklisICES @pcrjoana @NikkiTaylorJNCC @neil-ices-dk
> 
> Here is the final updated version of the metadata guidance for checking before we re-publish. Could you check the content to make sure it reflects the workflow and makes sense.
> 
> Thanks, Niki [JCDP.Metadata.Standard_User.guide_PubV1.3.docx](https://github.com/ices-tools-dev/cetaceans/files/8738663/JCDP.Metadata.Standard_User.guide_PubV1.3.docx)

@PeriklisICES @pcrjoana @neil-ices-dk @NikkiTaylorJNCC

Metadata guidance is ready for review before we re-publish. Could this be looked at by the end of today (30th May).

**Comment by NikiClear** [comment]
> @NikiClear I just had a read throughout the document and I don't have any suggestions. I appreciate the encouragement for the submitters to run the validation themselves first :)

Thank you @PeriklisICES. The updated metadata guidance has been submitted for re-publication and will be online on Tuesday 7th.
