### ISSUE TITLE
Download data from the  JCDP portal (DOWNLOAD)

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/cetaceans#248]
Have done a draft of the download facility.
It's not finished yet, the intention is to have a drat to talk about it in the next meeting, here is the draft:

![image](https://user-images.githubusercontent.com/8705477/155733229-b8746d59-d820-4c79-8602-12deff08fdfa.png)

Link to an example of the download: [https://cetaceans.ices.dk/Download/cf792e21-0bf5-4c42-9030-1e3152d544d0](https://cetaceans.ices.dk/Download/cf792e21-0bf5-4c42-9030-1e3152d544d0)

This page is now also linked with the inventory page: [http://cetaceans.ices.dk/inventory](http://cetaceans.ices.dk/inventory)

![image](https://user-images.githubusercontent.com/8705477/155733787-bbafb67a-c902-40ce-83a3-460a13d6ca17.png)

**Comment by neil-ices-dk** [comment]
### Disclaimer

Please acknowledge the following conditions before downloading data.


- All data products are by default publicly available, including those derived from restricted data.

- Only summary information for restricted records are publicly available for download

- All public data are under the Creative Commons (CC BY 4.0) licence.

- You have sole responsibility for correct and appropriate data interpretation.

- Results, conclusions, and/or recommendations derived from the data do not imply endorsement from ICES.

- You are requested to inform ICES of any suspected problems in the data.

The full ICES data policy and terms of use can be viewed [here](https://ices.dk/data/guidelines-and-policy/Pages/ICES-data-policy.aspx)



### Restricted Data

Some data within the ICES Cetaceans Database may be classified as restricted as determined by the data provider. These data are under the ICES Biodiversity Licence (link[ https://www.ices.dk/sites/pub/Publication%20Reports/Guidelines%20and%20Policies/ICES-Data-Licence-Biodiversity.pdf](https://www.ices.dk/sites/pub/Publication%20Reports/Guidelines%20and%20Policies/ICES-Data-Licence-Biodiversity.pdf))

The Responsible Organisation and Point of Contact is provided for each restricted survey, to enable the Data User to make a request direct to the Point of Contact.

**Comment by neil-ices-dk** [comment]
- add 'name' for request
- generate subject from request
- remove redundant text
- remove custodian emails
- split page into two tables (public and then restricted)
-
@cmspinto to make a 2nd draft based on this for review

**Comment by cmspinto** [comment]
The following changes are done:

- add 'name' for request
- generate subject from request
- remove redundant text
- remove custodian emails (for public data)
- split page into two tables (public and then restricted) 

We should check again this second draft in the next meeting, but in the meanwhile any comments and ideas are very welcome.

Note: We need some restricted data to be able to fully evaluate this page and the download.

**Comment by NikkiTaylorJNCC** [comment]
@cmspinto could we now please remove 'beta' from the JCDP portal pages?

**Comment by cmspinto** [comment]
Done

**Comment by neil-ices-dk** [comment]
latest version of download
https://cetaceans.ices.dk/Download/1f5fe2e8-25f1-4399-b1be-4e9623ed8d9d
![image](https://user-images.githubusercontent.com/23527005/160094413-e37498e4-0440-4cae-809b-7d7aaae97706.png)

### Text:

Download data from the cetaceans database.

This is the ID of your download: 1f5fe2e8-25f1-4399-b1be-4e9623ed8d9d

You can access this page to view the state of your download request: 
https://cetaceans.ices.dk/Download/1f5fe2e8-25f1-4399-b1be-4e9623ed8d9d 

To gain access to restricted data, provide your email and a small message in the form below, and this will be sent to all the contacts of the Data Custodians that have restricted data in your download.
Your request will be saved in the system for two months after that you might need to initiate a new request.
For any further questions, please contact [accessions@ices.dk](mailto:accessions@ices.dk).

1. Remove 'OR'
2. button text: "Available for Download now: x of x surveys"
3. move download button to the top of table
4. text for form: "Please fill in this form to request restricted data"
5. Blue button for form text "Send message"

**Comment by cmspinto** [comment]
Most of the changes have now been done, please give feedback about the changes to the page:

![image](https://user-images.githubusercontent.com/8705477/160128668-ef2e39eb-2a99-4687-84eb-5cee302c4a22.png)

Link to a download that only has restricted data:[https://cetaceans.ices.dk/Download/1c03fc4c-9b16-4eb0-b716-d2a9025ea109]( https://cetaceans.ices.dk/Download/1c03fc4c-9b16-4eb0-b716-d2a9025ea109)
Link to a download that only has Public data: [https://cetaceans.ices.dk/Download/b30b45eb-1956-4c48-95b0-769f594270b2](https://cetaceans.ices.dk/Download/b30b45eb-1956-4c48-95b0-769f594270b2)

Link to a page with Restricted and Public data: [https://cetaceans.ices.dk/Download/1f5fe2e8-25f1-4399-b1be-4e9623ed8d9d](https://cetaceans.ices.dk/Download/1f5fe2e8-25f1-4399-b1be-4e9623ed8d9d)

**Comment by neil-ices-dk** [comment]
thanks Carlos; this is the agreed text:

> To access restricted data, provide your email and a small message in the form below, and this will be sent to the Data Custodians contacts that have restricted data in your download.

**Comment by cmspinto** [comment]
This is how currently it is looking the email: 
![image](https://user-images.githubusercontent.com/8705477/160363868-fb376145-e081-4f7c-8ce6-1252532ee130.png)

A question is, should we put the download requested in cc?

This is how it currently looks the page to accept or reject the download request:
![image](https://user-images.githubusercontent.com/8705477/160364466-9a63bbc5-cc1d-430c-b60f-703bc8b65e49.png)

**Comment by neil-ices-dk** [comment]
@cmspinto can you send the email in plain text so we can suggest edits, thanks :)

**Comment by cmspinto** [comment]
> thanks Carlos; this is the agreed text:
> 
> > To access restricted data, provide your email and a small message in the form below, and this will be sent to the Data Custodians contacts that have restricted data in your download.

Sorry, the print screen was old!
![image](https://user-images.githubusercontent.com/8705477/160436803-3554ffe5-1c93-4492-a786-e3ed8cf82153.png)

**Comment by NikkiTaylorJNCC** [comment]
> > thanks Carlos; this is the agreed text:
> > > To access restricted data, provide your email and a small message in the form below, and this will be sent to the Data Custodians contacts that have restricted data in your download.
> 
> Sorry, the print screen was old! ![image](https://user-images.githubusercontent.com/8705477/160436803-3554ffe5-1c93-4492-a786-e3ed8cf82153.png)

Could we have a small change:
From: 
To access restricted data, provide your email and a small message in the form below, and this will be sent to the Data Custodians contacts that have restricted data in your download.
To:
**To access restricted data, please provide your email and a short message outlining your intended use of the data in the form below, and this will be sent to the Data Custodian contacts that have restricted data in your download.**

**Comment by cmspinto** [comment]
A receipt is sent to the user when the user makes the request for restricted data:
![image](https://user-images.githubusercontent.com/8705477/160831718-bf6f4f87-4469-4278-96cb-de9076c41a49.png)

**Comment by cmspinto** [comment]
An email is also sent when a data custodian approves or request a request, this is the text of the email:

         _Thank you for your request to access the restricted Cetaceans data records. Your request have been updated.
  
         You can check the status per survey at: [https://cetaceans.ices.dk/Download/bd7afd7c-0e34-4a5d-bf6e-37e1416b9312](https://cetaceans.ices.dk/Download/bd7afd7c-0e34-4a5d-bf6e-37e1416b9312)
         
         If you have any further questions, please contact accessions@ices.dk._

**Comment by cmspinto** [comment]
The data custodian can accept or reject the request and save a comment to the database:

![image](https://user-images.githubusercontent.com/8705477/160832684-7e2dcb5a-77bc-48fe-8b5a-157afbb4fe83.png)

**Comment by NikkiTaylorJNCC** [comment]
I still only see this view when I try to view the data:
![Download](https://user-images.githubusercontent.com/73958396/160859535-4ad260d4-7849-4e9c-82b3-d4f655abc488.png)

**Comment by NikkiTaylorJNCC** [comment]
> The data custodian can accept or reject the request and save a comment to the database:
> 
> ![image](https://user-images.githubusercontent.com/8705477/160832684-7e2dcb5a-77bc-48fe-8b5a-157afbb4fe83.png)

Where is states 'write your comment here if you have a comment' - can we please note it is mandatory to submit information about rejected requests and link the form: https://forms.office.com/r/1eBhaY6JMj

**Comment by NikkiTaylorJNCC** [comment]
> very good, is the comment mandatory (it probably should be...)?

Yes, mandatory - and i've put the link in the comment above for the form they should complete

**Comment by neil-ices-dk** [comment]
Hi all, do we need the separate form, wouldn't it be better to incorporate on this page and not as a separate form/set of data (we have all the information barring the reason for rejection)

**Comment by NikkiTaylorJNCC** [comment]
> Hi all, do we need the separate form, wouldn't it be better to incorporate on this page and not as a separate form/set of data (we have all the information barring the reason for rejection)

If we can make this mandatory for rejections and request a summary of why the request was rejected, then yes.  We can update and republish the data guidance to reflect that (our turn to republish now!) and remove the form link. Where will the information go? Can it be pinged to marinemammals@jncc.gov.uk?

**Comment by neil-ices-dk** [comment]
i think that would be a better way to go (pending Carlos agreeing to implement that) 😉

**Comment by neil-ices-dk** [comment]
what we need in the inline form as part of the 'accept/reject' request:
- Data Custodian (rejecting request)
- List of surveys
- Who requested (email)
- Reason for Rejection (freetext) - MANDATORY field

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/162197801-6644f586-988f-4e86-9f53-112b1d82f2ff.png)
please change to DOI URL
and add link to additional guidance: https://hub.jncc.gov.uk/assets/1b35ddf6-c469-4bf8-8300-86ec21da1c2d#jcdp-data-guidance-v1-0.pdf

**Comment by cmspinto** [comment]
Done, the URL is now the DOI, but the download button is not visible to not easy to test this.

**Comment by NikkiTaylorJNCC** [comment]
![image](https://user-images.githubusercontent.com/73958396/165301231-3293c59f-3c98-49b1-81fe-1346fdc0b5df.png)
@cmspinto could we change the text that is displayed when you filter the data and no submissions are returned?  Currently: 'sorry, you have no submissions to the database!'
Change to something like:
'There are no records matching your filters'

**Comment by cmspinto** [comment]
Need help on this one to know what is missing to publish the download?

**Comment by neil-ices-dk** [comment]
- platform codes needs to be updated to 'real' one 
- metadata needs to be published
- testing of download (format, disclaimer)

**Comment by neil-ices-dk** [comment]
- platform codes for submitted data are in order but @pcrjoana to double check CEFAS endeavour (74E9) 
- label in inventory download should say 'approved' and 'public'
- Rejection page should have a text that states that the comment box message is only viewable to the JCDP governance group, and is not provided to the data requestor

**Comment by cmspinto** [comment]
Approved and Public implemented.
![image](https://user-images.githubusercontent.com/8705477/170669180-7a535f91-e5ef-4db8-82cf-045e7ba729bb.png)

The email also goes now to the data custodian. So the download can be tested now.

**Comment by neil-ices-dk** [comment]
admin console here https://cetaceans.ices.dk/admin/ 
![image](https://user-images.githubusercontent.com/23527005/172611236-fe08155c-0c77-4b84-91cc-c1a6e213d106.png)

##adjustments
typo wiht = with
add title to 'delete' column
sort the list of orgs in dropdown

**Comment by neil-ices-dk** [comment]
data submitters should be invited to test the download function; so they understand the process, and also get some trust in the way it works
@NikkiTaylorJNCC

**Comment by neil-ices-dk** [comment]
@cmspinto to clear down the download list so we are at ground zero
