### ISSUE TITLE
As a Data user I want to be able to search the data portal (species/species group, location, time period) ..so that I can see what data is in my area/time of interest

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#25]
original id#22

Scoping/filtering viewing data - not actually accessing. #54 is about accessing

**Comment by cmspinto** [comment]
Comes back to the filters discussion, see issues: #65, #58, #55, #28

**Comment by LynnHeeley** [comment]
Steering Group Meeting 26th March: fields agreed see #32, filters on each field header
