### ISSUE TITLE
Metadata publication workflow

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#253]
- Remind metadata creators that they need to 'enable workflow' to push them for approval
- Periklis to make a technical check of the 88 records (with Niki)

**Comment by neil-ices-dk** [comment]
Periklis and Niki will catch up next week (w/c 11th April)

**Comment by neil-ices-dk** [comment]
link to the main catalogue: https://gis.ices.dk/geonetwork/JCDP/eng/catalog.search#/home 

@neil-ices-dk to add the link to the cetaceans landing page

@PeriklisICES to have a look why the child records are visible through the main meta record for the JCDP portal

**Comment by neil-ices-dk** [comment]
### Workflow for Metadata sign-off
1) checklist for conforming metadata which is based on the metadata guidance document
2) Roles: in the next 6 months, responsibility lies with Periklis with support from Joana and Niki C to review these on a weekly basis;

**Comment by PeriklisICES** [comment]
The child records were appearing because of a geonetwork bug. I made a ticket and it has been addressed.
https://github.com/geonetwork/core-geonetwork/issues/6289
Changes however, will show in the next software update. I am not sure when that will be.
Also, the workflow now sends emails automatically. If a second person can verify this, that would be great.

**Comment by neil-ices-dk** [comment]
test for marinemammals@jncc.gov.uk

**Comment by neil-ices-dk** [comment]
ca. 80 in total, Periklis has now reviewed about 20 of these and made background fixes
- feedback to data providers to ensure linkage
- workflow used to provide specific feedback on desired changes

meta data guidance will be updated accordingly

**Comment by NikiClear** [comment]
@PeriklisICES @pcrjoana @neil-ices-dk @NikkiTaylorJNCC 

Metadata guidance is ready for review before we re-publish. Could this be looked at by the end of today (30th May). It can be found here - https://github.com/ices-tools-dev/cetaceans/issues/247#issuecomment-1132743614

**Comment by PeriklisICES** [comment]
Done. Should we close this?
