### ISSUE TITLE
MEDIN compliance

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#255]
Amber for:
- Projection
- Transformation

MEDIN have suggested putting this in the data standard itself. This has caused some confusion as the projection information (which is part of the metadata standard) allows you to re-project according to any standard. ICES is not transforming the incoming data, so it is not clear what the value of this additional information is

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC awaiting response from MEDIN whether they are ok with this

**Comment by neil-ices-dk** [comment]
still with Nikki, awaiting some final conversations

**Comment by NikkiTaylorJNCC** [comment]
MEDIN now content with the data standard - @NikiClear is updating the document to reflect this and we will republish and do some comms.

**Comment by neil-ices-dk** [comment]
now published!
