### ISSUE TITLE
Map inventory: aggregation level

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#256]

**Comment by neil-ices-dk** [comment]
the standard used in VME's and also for Fishing Activity (VMS data) is a C-square grid of 0.05 ca. 
"a spatial unit used by ICES: 0.05 x 0.05 degree grid, equivalent to approximately 15 km² at 60°N latitude)"
https://en.wikipedia.org/wiki/C-squares

example from https://vme.ices.dk/map.aspx (off the West coast of Ireland)
![image](https://user-images.githubusercontent.com/23527005/164652652-75b31d65-994a-4b7e-8913-40f866ad46c5.png)
 
@NikkiTaylorJNCC to confirm with Steering Group

**Comment by neil-ices-dk** [comment]
so far there have only been positive responses. Will wait for the 6th May before we commit this decision.

**Comment by cmspinto** [comment]
We have talked about this and because it could be that part of the data is restricted and other part is open then it is preferable to link the map with the inventory instead of allowing to connect the map with the API for downloading the data.

**Comment by mehdiabbasi** [comment]
Some issues to discuss:
1. Order of filtering
2. Default filter to show the map  on loading
3. Style
4. Download link & Disclaimer

**Comment by neil-ices-dk** [comment]
> Some issues to discuss:
> 
>     1. Order of filtering
- each criteria are independent, so the order is not critical

>     2. Default filter to show the map  on loading
- no filter, show all data
 
>     3. Style
(reference layer)
- Number of records = Number of Observations (in each c-square)
- Colour code each c-square by percentiles based on high-low observation count

>     4. Download link & Disclaimer
- map will pass criteria to download page.

**Comment by neil-ices-dk** [comment]
Final strawpoll is that data providers are fine with the 0.05 c-square, so this is the default unit.

**Comment by mehdiabbasi** [comment]
the beta version of map is ready to test. Please use this link [https://cetaceans.ices.dk/viewonmap](https://cetaceans.ices.dk/viewonmap)

**Comment by neil-ices-dk** [comment]
@NikiClear to send example of map zoom thing
@NikkiTaylorJNCC to ask jon if there is a preferred colour palette for accessible legend 
-----
 
1. change 'class' in legend to 'survey', and title of legend to No. of Surveys
2. colours - orange hues, outline in same colour
3. when criteria are changed, the 'update' button needs to be highlighted i.e. change to Green
4. geographical filter: logic should be that you EITHER filter by ICES ecoregion OR by OSPAR regions
5. for drop down filters - add text 'Please select'
6. Add OSPAR and Ecoregion reference layers as base map layers that can be made visible/invisible
7. Add title for filters (for clarity)

**Comment by NikkiTaylorJNCC** [comment]
@mehdiabbasi @cmspinto Text to go in the white space above the map:

'Map view - inventory of the cetaceans database sightings and effort. This tool can be used to filter data to download'

...and on the inventory page change the text to 'Inventory of the cetaceans database - here you can filter data to download'
Thanks!

**Comment by mehdiabbasi** [comment]
Titles updated

**Comment by neil-ices-dk** [comment]
thanks @mehdiabbasi 
I would suggest that this page is ready to go live ahead of the download being signed-off (the subtitle is slightly misleading but i think we can live with that in the short term until the download is ready)
@NikkiTaylorJNCC do you agree that we can link this in to the main page now?

**Comment by NikkiTaylorJNCC** [comment]
Can we remove the (s) from criteria in the above screen shot?

But yes @neil-ices-dk we can get the link up and we'll flag with the SG.

**Comment by neil-ices-dk** [comment]
ok, map is now linked from landing page

**Comment by NikiClear** [comment]
@cmspinto @neil-ices-dk @NikkiTaylorJNCC @pcrjoana @mehdiabbasi 

The published map view seems to be an older version than what we reviewed during the last meeting. 
![image](https://user-images.githubusercontent.com/87769388/170683718-ae53f7ad-e409-4f6c-ac1a-fc55974810af.png)


I've noticed that SCANS surveys seems to be counted multiple times in the map, where I think this shouldn't be the case. I've checked the data in the template and I can't see duplication in the data. Could you look to see why SCANS might be counted multiple times in each map cell. If this is a problem with the data, I'll correct and re-upload.

**Comment by cmspinto** [comment]
Hi Nikki,

thanks for the heads up, have pull the changes and now the map is the last version:

![image](https://user-images.githubusercontent.com/8705477/170722814-72cc29c4-164d-47fe-9ce5-2346072be3f5.png)
