### ISSUE TITLE
Disclaimer for download

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#258]
from standard txt, create a modified version of the standard
https://github.com/ices-tools-dev/cetaceans/blob/main/cetaceans-Disclaimer.txt

**Comment by neil-ices-dk** [comment]
Hav edited disclaimer

**Comment by cmspinto** [comment]
Good progress, have included this draft version for now in the download.

**Comment by neil-ices-dk** [comment]
> Good progress, have included this draft version for now in the download.

thanks Carlos - there were some 'auto-fill' fields i.e. the specific data rights holders list that should be generated on the fly, is that part of your consideration

**Comment by cmspinto** [comment]
Yes:

![image](https://user-images.githubusercontent.com/8705477/168978173-65063605-728b-443e-af47-b14ab7e598e0.png)
