### ISSUE TITLE
As a Data user I want to access the data I need programmatically (eg using code via API) ..so that I can create robust processes to semi-automate the generation of statistics

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#26]
original id#23

Join up with a web/data manager ticket

Non geospatial APIs - clarify.

has a duplicate ticket #100
added MVP label as its 'in the ICES bag'

**Comment by cmspinto** [comment]
This relates to the creation of a WebAPI

**Comment by LynnHeeley** [comment]
Steering Group Meeting 26th March suggested: Input data (search criteria): species, month/year, location, surveytype, targettaxa, sea conditions and output data (get all fields every time as a flat single dataset, includes recordtype which can be filtered by).
