### ISSUE TITLE
Platform code expediting

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#260]
@pcrjoana to talk with Anna O to see if we can suggest a process like we have for JCOMMOPS

**Comment by pcrjoana** [comment]
Don(ald) Collins at NOAA has been contacted to request fast track approval of platform codes associated with JCDP, as long at it's not research vessels. Ie, even if Don agrees with the fast approval of JCDP vessels, research vessels will still have to go through him and will be excluded of the expedited approval process.

**Comment by NikkiTaylorJNCC** [comment]
Great, thanks for progressing this. Do we know what the definition of 'survey vessel' is in this case?

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC 
What I mentioned is related to the platform class vocabulary.

Vessels of opportunity and boats/sailing vessels might be fast tracked if Don agrees, but research vessels always need his approval. The research vessel class is defined as:

"A platform of any size operating on the surface of the water column in unpredictable locations that is specifically equipped, manned and operated for scientific, usually oceanographic, research"

You can consult the whole vocabulary [here](https://vocab.seadatanet.org/v_bodc_vocab_v2/browse.asp?order=conceptid&formname=search&screen=0&lib=l06&v0_0=&v1_0=conceptid%2Cpreflabel%2Caltlabel%2Cdefinition%2Cmodified&v2_0=0&v0_1=&v1_1=conceptid&v2_1=3&v0_2=&v1_2=preflabel&v2_2=3&v0_3=&v1_3=altlabel&v2_3=3&v0_4=&v1_4=modified&v2_4=9&v0_5=&v1_5=modified&v2_5=10&x=54&y=25&v1_6=&v2_6=&v1_7=&v2_7=)

**Comment by NikkiTaylorJNCC** [comment]
Great, that should keep the number of vessels having to go via Don to a minimum (if they agree!). Fingers crossed.

**Comment by pcrjoana** [comment]
Great news! Don from NOAA agreed on this. I've already contacted our colleague Mehdi, who develops the platform request facility, to talk about which is the best way forward development wise. 
This basically means that, after Mehdi has developed the new feature, JCDP vessels will have a processing time of 2 weeks, unless they're research vessels of course, in which case it'd be longer.

**Comment by NikkiTaylorJNCC** [comment]
AMAZING NEWS!!!!! That is fab. So...to discuss at the next sprint, but hopefully we can work towards all data in the system having the correct codes by the 1st week of June, and therefore go ahead with our 'launch' plans w/c 6th June... Happy days.

**Comment by pcrjoana** [comment]
Mehdi and I have set up a meeting for this Friday morning, so by the next portal I'll hopefully have some news on when we can start expediting JCDP ship codes. :-)

**Comment by pcrjoana** [comment]
Good news! The expedition of JCDP platform codes (other than research vessels) is now up and running. We've tested it and it's working as it should!

JCDP platform code approval time is now 2 weeks after being checked by a data manager.

It should be noted by requesters that they should enter "used for sampling data for the JCDP" in the notes.

**Comment by neil-ices-dk** [comment]
@NikkiTaylorJNCC to chase the organizations that have yet to submit platform code requests and cc: Joana
