### ISSUE TITLE
Map View - SCANS data aggregation issue

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#262]
Hi all, 

I've noticed that the map seems to be showing multiple surveys for SCANS within the grid cells. I've checked the data for duplication (showing 14 surveys within each cell). 
![image](https://user-images.githubusercontent.com/87769388/170728011-2ba4f994-f798-4dc5-b6bd-00134b2441ca.png)

I checked the data and didn't see any obvious duplication in the effort table. Could you check why the map might be showing 14 surveys in each cell? I'll continue to check the data uploaded - if this is a problem caused by the data I'll fix and re-upload.

**Comment by cmspinto** [comment]
Thanks Niki, it was a bug and it's solved now :)

![image](https://user-images.githubusercontent.com/8705477/172623620-c17a2967-1e10-4431-ba7b-e02c244f882f.png)

**Comment by neil-ices-dk** [comment]
ok closing this then 🤓
