### ISSUE TITLE
Platform codes

### ISSUE THREAD

**Issue by pcrjoana** [ices-tools-dev/cetaceans#268]
I am slightly worried that I haven't seen any new platform code requests for ships used to collect JCDP data.

My question is if we it's included in the guidance that submitters should put "Vessel used to collect data for the JCDP" in the notes, as we discussed before. It's important to have JCDP in the notes so that I can easily catch the requests and fast track them.

**Comment by neil-ices-dk** [comment]
Guidance is in place, in the platform request for ongoing new codes, it's important to flag:

> "Vessel used to collect data for the JCDP" in the notes
