### ISSUE TITLE
Restricted Data Download - user experience 

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#270]
reported by ellie@orcaweb.org.uk  (broken into 3 chunks below)

Hello, I've been testing the request/download process and this are some of the things I noticed: 

When we receive data requests, we can only see them and grant/deny them if we follow the link in the email and only the table header shows up with no information in it if I try to view the data requests via manage > view list of download requests. This could be a problem where the email goes into a generic, shared inbox where there are multiple people with access who might mistakenly delete incoming data requests as happened to me a few times as I was testing it. 

When I get the email back after I accept or deny my request, it only says it's been updated and when I follow the link, it only shows me the name of what I requested and not whether it's been accepted or denied and there is also no download link if I accept my request. I tried requesting the same data again in case that's how you download it once the request is accepted but it doesn't seem to be so I haven't been able to get a restricted dataset even if I unlock it for me (maybe I'm missing something though)? Seems to work fine for open access data. 

From a requester perspective, if you select Globicephala you just get sightings of unidentified Globicephala and not the sightings of pilot whales that have been identified to the species level as well which I think could confuse people who might be expecting unidentified pilot whales AND pilot whales identified to the species level. Similarly, if you ask for Delphinidae, you only get unidentified dolphins and not all the species that are in that family and so on. Hope this helps, Ellie

**Comment by neil-ices-dk** [comment]
> When we receive data requests, we can only see them and grant/deny them if we follow the link in the email and only the table header shows up with no information in it if I try to view the data requests via manage > view list of download requests. This could be a problem where the email goes into a generic, shared inbox where there are multiple people with access who might mistakenly delete incoming data requests as happened to me a few times as I was testing it.

Solution: @cmspinto to add a hyperlink to the data request against the requestID 'view data requested', and add a column for requester email

**Comment by neil-ices-dk** [comment]
> When I get the email back after I accept or deny my request, it only says it's been updated and when I follow the link, it only shows me the name of what I requested and not whether it's been accepted or denied and there is also no download link if I accept my request. I tried requesting the same data again in case that's how you download it once the request is accepted but it doesn't seem to be so I haven't been able to get a restricted dataset even if I unlock it for me (maybe I'm missing something though)? Seems to work fine for open access data.

This is a bug - when only restricted data needs to be refactored

![image](https://user-images.githubusercontent.com/23527005/183037715-bc93a1a1-3da5-4a7e-b5cf-3646b910b3c6.png)

**Comment by neil-ices-dk** [comment]
> From a requester perspective, if you select Globicephala you just get sightings of unidentified Globicephala and not the sightings of pilot whales that have been identified to the species level as well which I think could confuse people who might be expecting unidentified pilot whales AND pilot whales identified to the species level. Similarly, if you ask for Delphinidae, you only get unidentified dolphins and not all the species that are in that family and so on. Hope this helps, Ellie

to test in the dropdown: sort by taxon hierarchy and species within the order/family and then indent at each taxon level so that it is clear there is a nesting. When you select a higher taxon level, it should then select all taxon in the lower hierarchy. 

![image](https://user-images.githubusercontent.com/23527005/183040642-20ff71c8-d22b-4ac6-8a8d-13f754bcd5b1.png)

**Comment by cmspinto** [comment]
We have now a new proposal for the species  dropdown

Two of the main changes are: 

1.  it shows all the taxon with indication of what rank the display name is filtering.

2. The filter will apply to the records of that rank but also so all the children of that rank, example: a filter of Balaenopteridae  (Family) will filter for all the records submitted of that species. 

![image](https://user-images.githubusercontent.com/8705477/186375430-ff139afe-b570-4f15-9dfa-52c803b4ddf7.png)

**Comment by neil-ices-dk** [comment]
thanks @cmspinto the functionality looks good. The one thing that would make logical sense is if the sorting of the different hierarchies was based on the order/family/species etc. So in your example the list would appear:

.....
Balaenopteridae (family)
Balaenoptera (genus)
Balaenoptera Borealise (species)
....etc.

the title of the dropdown would also need to change to 'taxonomic classification' or something like that

**Comment by cmspinto** [comment]
Sorry, can we talk this in the meeting? 

I think I know what you mean, but if we could talk it in the next sprint would be good.

**Comment by neil-ices-dk** [comment]
@cmspinto remove these levels:
![image](https://user-images.githubusercontent.com/23527005/187630648-8f1e1261-1ea7-4d3d-9294-dd0699a966ad.png)

**Comment by cmspinto** [comment]
Done.

![image](https://user-images.githubusercontent.com/8705477/187643052-388154f2-2cf5-4c29-9bcc-c733e8bd5d1e.png)

**Comment by cmspinto** [comment]
Done.
