### ISSUE TITLE
WGJCDP first meeting - agenda

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#271]
first online meeting set for 15th September, 13:00 UK time dur. 3 hours

**Comment by NikiClear** [comment]
First draft of agenda, please provide feedback and suggested agenda items.
[WGJCDP_2022 September_Agenda_v1.docx](https://github.com/ices-tools-dev/cetaceans/files/9267210/WGJCDP_2022.September_Agenda_v1.docx)

**Comment by neil-ices-dk** [comment]
Thanks @NikiClear
I think the Agenda touches on all the major things, i would be a bit concerned looking at the timings and whether it is realistic to cover all of the headings i.e. the 14:15 45 min slot covering data products, harmonisation with ESAS etc. seems like it might need more time for discussion. At this meeting, will you start to assign/volunteer people for difference aspects of the ToR's as that might help from the start to spread the tasks/responsibility out.

**Comment by NikiClear** [comment]
> Thanks @NikiClear I think the Agenda touches on all the major things, i would be a bit concerned looking at the timings and whether it is realistic to cover all of the headings i.e. the 14:15 45 min slot covering data products, harmonisation with ESAS etc. seems like it might need more time for discussion. At this meeting, will you start to assign/volunteer people for difference aspects of the ToR's as that might help from the start to spread the tasks/responsibility out.

Thanks Neil, I have extended that section to 1 hour and moved the ESAS item to AOB as it'll just be an introduction to the issue during this first meeting. 

Having spoken to Nikki, I believe this initial meeting will have more of an introduction to the JCDP and WG. With a plan for the next (longer) meeting to start organising volunteers/sub-groups who can focus on aspects of the TOR. But can discuss during the sprint tomorrow.
