### ISSUE TITLE
Data request process

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#284]
@neil-ices-dk @cmspinto @NikkiTaylorJNCC 
The data request process was tested with SWF and HWDT to check the process works and the steps/instructions are clear for the data custodians. 

HWDT provided some written feedback, which will need to be investigated and addressed. 
[HWDT JCDP Testing feedback_20221111 (1).docx](https://github.com/ices-eg/WGJCDP-Cetaceans/files/10011611/HWDT.JCDP.Testing.feedback_20221111.1.docx)

**Comment by neil-ices-dk** [comment]
button changed to make more obvious;
