### ISSUE TITLE
download statistics

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#285]
@cmspinto Good to see some stats starting to come out; does this exclude ICES IP’s?

![image](https://user-images.githubusercontent.com/23527005/204738487-50efa1df-9680-41a1-b652-57ced295e3ee.png)
![image](https://user-images.githubusercontent.com/23527005/204738514-132d1a7f-8c2c-449b-91f3-400bdf842297.png)

**Comment by cmspinto** [comment]
@neil-ices-dk we do not keep track of the IP addresses in the database. 

So to answer your question this is all IP addressees

**Comment by neil-ices-dk** [comment]
ok, so we would need to look at the Google dashboard to gauge how many go to the download page (and from where) to qualify the stats above. @Terhinator please note we are in need of that dashboard soon...thanks!

**Comment by Terhinator** [comment]
Ok, Nas has created the dashboard so we should be able to pull information from it. When do you need this exactly? Next week ok?

**Comment by neil-ices-dk** [comment]
> Ok, Nas has created the dashboard so we should be able to pull information from it. When do you need this exactly? Next week ok?

next week would be great :)

**Comment by neil-ices-dk** [comment]
will pick up in Dashboard #241

**Comment by cmspinto** [comment]
This will be picked up in the Analytics.
