### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/cetaceans#286]
The ICES librarian has asked if we can change the format to the standard citation format

From:
Joint Cetacean Data Programme (JCDP) (https://cetaceans.ices.dk/), 2022. ICES, Copenhagen

To: 
Joint Cetacean Data Programme (JCDP), 2022. ICES, Copenhagen. https://cetaceans.ices.dk

**Comment by cmspinto** [comment]
Done: 
![image](https://user-images.githubusercontent.com/8705477/205683081-2125c890-0229-4565-8fd7-8eb296039c0f.png)

**Comment by neil-ices-dk** [comment]
thanks @cmspinto it turns out that was not specific enough, see update below

Joint Cetacean Data Programme (JCDP), 2022. ICES, Copenhagen, **Denmark**. https://cetaceans.ices.dk/

**Comment by cmspinto** [comment]
Done 
![image](https://user-images.githubusercontent.com/8705477/206660462-873fc199-06ac-4680-9d82-edfcda224ea8.png)
