### ISSUE TITLE
Critical review of web content; Hub and Portal (pre WGJCDP meeting action for all)

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#289]
Related to April meeting agenda item 1

### Pre meeting action
All members to review the existing content to input to discussion for further development

- JCDP Hub - https://jncc.gov.uk/jcdp
- JCDP Data Portal - https://cetaceans.ices.dk/

**Comment by LM408** [comment]
@NikiClear thanks for sending these links, I think the JCDP Hub text is looking really good and I will have a bit more of a play around with the data portal prior to the next meeting to see if I have any suggestions but at the moment it looks quite user friendly and I think anyone familiar with navigating this type of portal should find it all very self explanatory - looking forward to taking a deeper dive!

**Comment by neil-ices-dk** [comment]
@NikiClear the Hub text is comprehensive, the below section needs updating as this reflects the pre-launch situation

> ### The JCDP Data Portal

> The JCDP Data Portal is a website which enables data providers to upload cetacean survey data into the JCDP Data Portal, and data users to explore data products and download datasets.

> [The International Council for the Exploration of the Sea (ICES)](https://www.ices.dk/Pages/default.aspx) has been contracted by JNCC on behalf of Defra, to build the Portal including the database and associated infrastructure to explore and access the data, which is hosted in the [ICES Data Centre](https://www.ices.dk/data/Pages/default.aspx).

> The JCDP Data Portal is planned to launch in spring 2022.
