### ISSUE TITLE
As a Data user I want to access the metadata for the datasets that I am using ..so that I know exactly what I can and can't do with the data

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#29]
original id#26

May delay things if included in MVP?

Is this related to data use permissions from eth data owner, or the information that gives you context to ensure appropriate use?

DISCUSS due to clarification on metadata/license

**Comment by cmspinto** [comment]
Need discussion and what kind of metadata is associated with the datasets.

**Comment by LynnHeeley** [comment]
ensure data is  used appropriately so that inappropriate analyses are not attributed to the data
