### ISSUE TITLE
Proposed change to JCDP standard: Change end time and location to optional for aerial surveys

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#292]
@cmspinto 

I've been processing SCANS aerial data and I've realised their data collection protocol does not capture end time and location of each error section. This is stopping me from uploading data as the EndTime, EndLatitude and EndLongitude fields in our Effort table are mandatory. It would be labour intensive and a potential to introduce error to try retrofit the data to our standard for these fields. 

Therefore, could the EndTime, EndLatitude and EndLongitude fields in the effort and environment table be made optional for aerial survey data please? 

@neil-ices-dk @NikkiTaylorJNCC

**Comment by neil-ices-dk** [comment]
Hi all - now that we have an operational system, this really should be a decision that needs to be passed by the WGJCDP (probably as a package of changes). In that way we keep the governance in the loop, and avoid too many incremental changes that may lead to new errors.

**Comment by NikiClear** [comment]
Agreed by WGJCDP in July 2023. Changes implemented in the database, template and data standard.
