### ISSUE TITLE
Request rejection form - check

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#295]
Could we confirm whether the data request workflow  includes a question for data custodian to explain the reasons when a data request has been rejected? While speaking with Orca, they seems not to be aware of the need to answer this question so we want to check this is in place and how it works. 

Related to #248 

If this is set up, how can Nikki/I/WGJCDP access the information from this ?

Unfortunately, I can check and test this myself as I'm not custodian of any restricted datasets. 
Thanks!

**Comment by cmspinto** [comment]
I have tested this feature and looks like it's working:

![image](https://user-images.githubusercontent.com/8705477/228244274-634eaec9-a389-41cc-b129-01f320861d5d.png)
