### ISSUE TITLE
Reference layer box on Map View - bug

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#300]
There seems to be a bug on the JCDP map view. 

When the 'reference layer' box overlaying the map is minimised, the map area below is not responsive (i.e. I cannot click and drag to move the map when I click on this area, the number of survey/observations information box does not show , and the polygon draw option doesn't respond in this area). But all work normally outside of the area below the minimised 'reference layer' box. 
This is a little hard to explain but will make sense when you try to use the left side of the map after the reference layer box has been minimised. 

Could the reference layer box be set to the minimised setting automatically, when the page is loaded (rather than expanded as it currently is) please?

**Comment by mehdiabbasi** [comment]
Hi @NikiClear, It is fixed

**Comment by NikiClear** [comment]
That's great. I've tested and is working for me. Thank you for looking at this so quickly.
