### ISSUE TITLE
Codes for unknown ships

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#304]
I have a problem which I need help to find a solution to

I'm working on data from the first SCANS survey in 1994 and CODA in 2007. I've managed to find the ship codes for most of the survey vessels, except four. There appears to be no more information available on these ships and I've looked through Marine traffic, Vessel Finder and the Maritime Database to try find the ships with no luck. 

SCANS	1994	Henny	
SCANS	1994	Corvette	
CODA	2007	Rari	
CODA	2007	Germinal	

To be able to upload the data collected from these ships, I need a ship code but the only information I have is the name of the ship and the rest of the information seems to be lost (the data custodian is looking for more, but isn't hopeful) 

@pcrjoana - Is the ship name only enough to submit to the Ship code vocabulary list? 
And if not, what options do we have to upload these data to the JCDP.

**Comment by pcrjoana** [comment]
If you don't have any other information on the ships, not even the flag, I don't think it's enough for a code. I'll get back to you on a solution on how to upload these data.

**Comment by pcrjoana** [comment]
@NikiClear it seems we really need the flag of the ship used to collect the data. Is this information the data submitter can find?

**Comment by NikiClear** [comment]
> @NikiClear it seems we really need the flag of the ship used to collect the data. Is this information the data submitter can find?

I don't think so, this information seems to be lost. Phil (from SCANS) is keeping an eye out but it's really doubtful more information will be found. But I'll ask again 

If not would there be any work around to get these data up without a ship code?

**Comment by pcrjoana** [comment]
Let me have a think about the solution. I'll bring it up with the other data managers to see if they have good suggestions. I think the best would be to use a code for unknown ships with the same flag as the submitting institute, but I'm not sure about this. We've had cases where this was done, and then it transpired that the ship didn't have the same flag as the institute.

**Comment by NikiClear** [comment]
> Let me have a think about the solution. I'll bring it up with the other data managers to see if they have good suggestions. I think the best would be to use a code for unknown ships with the same flag as the submitting institute, but I'm not sure about this. We've had cases where this was done, and then it transpired that the ship didn't have the same flag as the institute.

@pcrjoana 
I have some good news. We have the (most likely) flags for these ships so I'm hoping we can get them added to the Ship vocabulary? This is the only information we have about these though, so I'm hoping it will be enough. 

- Corvette: Denmark
- Henny: UK

**Comment by NikiClear** [comment]
Ship codes will be generated based on available information.
