### ISSUE TITLE
New web services - data products

### ISSUE THREAD

**Issue by NikiClear** [ices-tools-dev/cetaceans#308]
Produce web services showing summary of all data hold within the JCDP database, aggregated to C-Square scale. 

- Effort in km per C-square grid cell; showing two metrics 1. showing total effort in km in all sea states, and 2. where the sea state is <= 3
- Number of sightings/observations; as total number for all species and per species; where the sea state is <= 3
- Number of unique species recorded per grid (observed species richness); where the sea state is <= 3

**Comment by cmspinto** [comment]
@NikiClear  are these queries per year or in total?

For example, what filters do you want to specify when asking the query?
Year?
Species?

**Comment by NikiClear** [comment]
> @NikiClear are these queries per year or in total?
> 
> For example, what filters do you want to specify when asking the query? Year? Species?

That's a good question. 
Would it be possible to let the user select a date range (choose all data or between dates)? If not then perhaps to cover all bases, include all data and also per year?

**Comment by MariaMakri** [comment]
Hi Niki!

It is possible for the users to select which year(s) they would like to retrieve data for, so we can do it that way. 

Another question that appeared is regarding the unique species. There are some sightings that are not identified at a species level. There is an example in the excel file attached here (this is for one Csquare, only for year 2008). 

How do you think we should approach this? 

[cetaceans_webservices.xlsx](https://github.com/ices-eg/WGJCDP-Cetaceans/files/14932401/cetaceans_webservices.xlsx)

**Comment by NikiClear** [comment]
Hi Maria and Carlos

I think we would need to ignore the records which aren't recorded at species level, as the others chould be the same species or different but we would never know. 

So for the example you sent the species list would be 
- Balaenoptera physalus
- Delphinus delphis
- Globicephala melas
- Tursiops truncatus
- Hyperoodon ampullatus

or 5 unique species

**Comment by cmspinto** [comment]
An example of this webservice "Number of sightings/observations; as total number for all species and per species; where the sea state is <= 3" as a product:

https://[cetaceans.ices.dk/API/GetTotalSightingsperCsquareAndSpeciesAndYear](https://cetaceans.ices.dk/API/GetTotalSightingsperCsquareAndSpeciesAndYear)

**Comment by cmspinto** [comment]
Webservice of the data product (option of filtering per year or species): [GetTotalSightingsperCsquareAndYear](https://cetaceans.ices.dk/API/GetTotalSightingsperCsquareAndYear)

**Comment by cmspinto** [comment]
Two of the requested product are on-line:
[https://cetaceans.ices.dk/webservices](https://cetaceans.ices.dk/webservices)
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/e8614182-0043-4315-ae17-72cc6abba313)

Let me know if there are any comments or questions.

**Comment by neil-ices-dk** [comment]
@MariaMakri to test please

**Comment by MariaMakri** [comment]
@NikiClear I had a look and it seems that it is working, except for a typo that we need to remove in a all of them ('number' is duplicated). However, could you also have a look and confirm that this is what we were going for? It seems that you can select a string of several years, but not necessarily a range of them like (2014-2018). Would that be an issue?
