### ISSUE TITLE
As a Data user I want to understand what data may be available for my spatial area of interest ..so that I can see if there is data that I do not have access to and then request access

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#31]
original id#28

Data visualisation - considered a data product. 

Actually a visualisation of the data - not a product. Reject because there are other stories that cover this aspect

**Comment by cmspinto** [comment]
Making all data available at some level of aggregation?

**Comment by GMDuncan** [comment]
Moved into products based on advice from ICES
