### ISSUE TITLE
As a Data user I want to see basic summary information of the JCDP datasets so that I know what data are available (INVENTORY)

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#32]
### **Subgroup 2 suggests Phase 2**

original id#29

Ref #186

has been SPLIT - initial visualisation of what data are there (@neil-ices-dk would this be the map visualisation or another product? I think that this is different from the 'dashboard' idea for tracking stats/use isn't it?), and then time series information - trends in abund and dist?
relates to #17 and #126?

**Comment by cmspinto** [comment]
I think this need to be split into two, submissions summary and dataset summary

**Comment by LynnHeeley** [comment]
Steering Group Meeting 26th March: Table of all JCDP data. Fields are in image below plus location (ICES to generate – not needed in standard: EEZ) and temporal.
![image](https://user-images.githubusercontent.com/7250284/112857970-51bac700-90a9-11eb-84bf-e7c2ba422430.png)

•	Functionality required: Filters on each field (multiple entries can be checked - NOT single option only)
•	Download button at bottom - include disclaimer pop-up on download (favourite example from acoustic portal)
•	Restricted shown as surveyname but get token on download to request access

**Comment by LynnHeeley** [comment]
A list of datasets within the database presented in a filterable table with additional functionality. 

Examples:  https://biodiversity.ices.dk/Submissions, https://underwaternoise.ices.dk/continuous/submissions  https://ecosystemdata.ices.dk/stomachdata/download.aspx, https://acoustic.ices.dk/submissions  - each of these has useful elements that could be in a final product. 

Questions: 

What fields/functionality is required: 

filters: search, year, sort or filter on each field header 

link to metadata 

Download dataset 

Request access to restricted datasets (individually) 

Which fields?

**Comment by neil-ices-dk** [comment]
include #219 vessel size for consideration

**Comment by neil-ices-dk** [comment]
Good news for the weekend, have a draft of the inventory page, feedback is more than welcome 

[download](https://cetaceans.ices.dk/download)

**Comment by NikkiTaylorJNCC** [comment]
Thanks @cmspinto! Could we please change the display from data rights holder to data custodian? I think that will be more relevant across the board, and that is who they will converse with if data are restricted or if they want to collaborate etc.  If possible, it would also be good at this stage to be able to filter the platformclass and and targettaxa as well... so they can pick out aerial v ship based, and focussed cetacean survey from multi taxa survey. 
Assume the system will automatically assign the ecoregions to a dataset...

**Comment by neil-ices-dk** [comment]
agreed additions:
- change data rights holder to **data custodian**
- Include platformclass as filter (no column)
- targettaxa as filter (no column)
- 'reset filters' button

Thanks

**Comment by cmspinto** [comment]
The above filters and button were added:

**Comment by cmspinto** [comment]
I think we are missing a filter for data access, I think it would be handy if the user could filter only for open or restricted data.

**Comment by NikkiTaylorJNCC** [comment]
@cmspinto Thanks for making the changes. There's a nice gap just for the data access filter so please add it in :)

**Comment by neil-ices-dk** [comment]
new link https://cetaceans.ices.dk/inventory 

to change label
![image](https://user-images.githubusercontent.com/23527005/155983367-e6b567e0-af4c-48dc-be31-319adf03ddaf.png)

typos:
![image](https://user-images.githubusercontent.com/23527005/155983513-d921963e-12e1-4ea6-bb07-1dfdd004e00c.png)
criteria
download ;0)

add: data access filter

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/157045389-252d0ad4-65c5-412d-8212-20133956f23f.png)

Maybe we can we close this issue now?

**Comment by neil-ices-dk** [comment]
agreed fulfils MVC, @cmspinto please remove BETA label thanks

**Comment by neil-ices-dk** [comment]
@cmspinto text label rather than code for data custodian
@NikkiTaylorJNCC to consider grouping/aggregation params i.e. reporting year, custodian etc.

**Comment by neil-ices-dk** [comment]
@cmspinto are we missing a check box on the left hand to select specific surveys?

**Comment by neil-ices-dk** [comment]
add how many pages there are (or records)

**Comment by neil-ices-dk** [comment]
### Grouping suggestion

see https://esas.ices.dk/inventory? 

(where **campaigns** would be equivalent to **survey events**, and **data rights holder** would be **data custodian**)

**Comment by cmspinto** [comment]
Bugs should be corrected now and changes done:

![image](https://user-images.githubusercontent.com/8705477/165891163-c3537a10-ff61-48a0-bbf7-0f200f9abf8d.png)

The reason for Orca to have tow distinct records was indeed a distinct email, we need to improve our QC in the screeningm becasue it was not intended by ORCA, it is just a typo:
![image](https://user-images.githubusercontent.com/8705477/165891341-351ded14-35ee-4dfb-9a70-5367007b5e61.png)

**Comment by neil-ices-dk** [comment]
Typo in criteria
remove time from first/last survey
add metadata link to 'number of survey events'

**Comment by cmspinto** [comment]
All done except the metadata link, 

that is because the records in the database don't have a metadata record yet!

**Comment by cmspinto** [comment]
Checked and some of the records have metadata, but the result link is still not published:

![image](https://user-images.githubusercontent.com/8705477/167359848-a68992e8-56fb-4cf6-9312-fb52450c8252.png)


Another issue could be that submiters are creating a metadata for each survey record:

![image](https://user-images.githubusercontent.com/8705477/167360081-e3232d54-4b22-4fc7-ab87-fb29196f803e.png)

**Comment by neil-ices-dk** [comment]
rename in inventory:
- Start Date/End Date (for first survey and last survey)
- added survey name to inventory and link to metadata in Geonetwork (via URL)

**Comment by cmspinto** [comment]
Changes done, looking like this:

![image](https://user-images.githubusercontent.com/8705477/168992761-6fea8271-367b-4e39-ac43-2049ddd29320.png)

**Comment by cmspinto** [comment]
Download and emails have the same summary table now:

https://cetaceans.ices.dk/Download/56b397d8-a66d-48c8-bc3c-67af415c57eb

![image](https://user-images.githubusercontent.com/8705477/172319812-b6f7c261-7a7f-4d5e-83e2-1cf8014a50dc.png)
