### ISSUE TITLE
CLARIFY PURPOSE: As a Data user I want to be able to filter visualisations for date and species ..so that I can use the visualisation page for graphing the full dataset

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#34]
original id#31

Purpose "so that" needs clarifying in the context of the task, but initial task makes sense. E.g. "Full data" is ambiguous.

**Comment by cmspinto** [comment]
A summary table with option of filtering per date and species?

**Comment by LynnHeeley** [comment]
partial duplicate of #65
