### ISSUE TITLE
As a Data user I want to be able to download the chart/visualisation ..so that I can use it in a report (correctly attributed/referenced)

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#35]
original id#32
Download of a static graphic?

**Comment by cmspinto** [comment]
Needs to be discussed if this is a priority

**Comment by LynnHeeley** [comment]
Graphs/charts to be discussed later in the project. likely to want a png or other file format of the chart that is viewed.
