### ISSUE TITLE
As a Data user I want to be able to download all the fields that were originally submitted ..so that I can use all the data fields that are held

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#36]
original id#33
Doesn't take into account fields that are redacted under restriction.

**Comment by cmspinto** [comment]
This is part of the download format, it can be the same as the upload one?

**Comment by LynnHeeley** [comment]
yes same/equal to input  - see #194 for formats

**Comment by LynnHeeley** [comment]
plus submission date #38
