### ISSUE TITLE
As a Data user I want to be able to explain why I need the data when requesting access to restricted data ..so that the process is quicker and I can have the best chance of being granted permission to access the data I need

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#45]
original id#42
include in the email/form if provided - under discussion

**Comment by cmspinto** [comment]
See issue #50

**Comment by neil-ices-dk** [comment]
@kellymacleod the formulation of the user story is really worrying; it suggests that data access is really hanging on how well you can argue your case :(

the default position from ICES is the 'email contact' like we have for VME; 

we have talked about a possible solution that would work something like this:
- a user clicks on download and is notified that the data are restricted and is given the contact email(s) of the data provider
- the user also is given a token 
- at the same time, the provider is notified that there is a request and should then enter a discussion when contacted by the requester about the use case
- the data provider is also given a link and token
- if the data provider AGREES to the request, he can provide the token/link to the data user to download the restricted data

this way, we keep the negotiation largely out of the ICES system but also make it easy for the data provider to provide access.

**Comment by LynnHeeley** [comment]
![token](https://user-images.githubusercontent.com/7250284/107240025-5eb02800-6a21-11eb-803d-0a0f85ae1d57.png)
