### ISSUE TITLE
As a Data user I want to be able to save my 'search' whilst I request permission for all datasets in my area of interest ..so that I can get back to it easily once permission is provided

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#48]
original id#45
GDPR issues re saving the IP address - not possible in ICES
registered login would get around this - which does not currently exist in ICES

**Comment by neil-ices-dk** [comment]
@LynnHeeley see possible solution in #45 which would address this;

**Comment by LynnHeeley** [comment]
solutions in #45 and #58 . labelled duplicate and closed
