### ISSUE TITLE
data input format

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/cetaceans#49]
We are starting from the draft given. 

Added comments and will move to the next stage where we:
* [x] Find how many records are needed for the format
* [x] Agree in the fields for each record
* [x] Link the agreed vocabularies (this might require another issue)
* [x] Have the initial QC needed to start screening the first files

**Comment by cmspinto** [comment]
[ICES_DraftFormat.xlsx](https://github.com/ices-tools-dev/cetaceans/files/5548112/ICES_DraftFormat.xlsx)
[JCDP DataStandard V2.4.docx](https://github.com/ices-tools-dev/cetaceans/files/5548113/JCDP.DataStandard.V2.4.docx)

**Comment by kellymacleod** [comment]
[JCDP DataStandard V2.4_KM.docx](https://github.com/ices-tools-dev/cetaceans/files/5555529/JCDP.DataStandard.V2.4_KM.docx)

Some responses to your comments on the draft JDCP standard. If they don't make sense, let's pick up with a call

**Comment by neil-ices-dk** [comment]
> 
> 
> [JCDP DataStandard V2.4_KM.docx](https://github.com/ices-tools-dev/cetaceans/files/5555529/JCDP.DataStandard.V2.4_KM.docx)
> 
> Some responses to your comments on the draft JDCP standard. If they don't make sense, let's pick up with a call

Looks good Kelly - some good Q&A, will wait for the full response from the team 👍

**Comment by neil-ices-dk** [comment]
also see agree action from meeting #99

**Comment by neil-ices-dk** [comment]
@pcrjoana to update this ticket with information on the final agreed data standard after your meeting with Nikki

**Comment by neil-ices-dk** [comment]
- Format is agreed and Joana has started adding to the ICES DATSU system;
- [DATSU link to format](http://datsu.ices.dk/web/selRep.aspx?Dataset=149)
- @pcrjoana to add final data standard document here

**Comment by pcrjoana** [comment]
Format inserted in DATSU. 
Joana to finalise the data standard document.

**Comment by neil-ices-dk** [comment]
> Joana to finalise the data standard document.
thanks @pcrjoana we should perhaps host the documents on community.ices.dk as they will develop over time (maybe under WGMME for the time being)

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC and @neil-ices-dk I'm a bit late with the data standard document, but it should be updated by the end of this week. It's a bit more work than I originally estimated!

**Comment by neil-ices-dk** [comment]
data standard document will be updated and distributed with members of the JCDP consortium 24/09

**Comment by cmspinto** [comment]
Users can now screen their files:

https://cetaceans.ices.dk/manage/ScreenFile

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC sent an updated data standard on 02/11. Joana to ask for minor clarifications on the 04/11 sprint.

Also to be brought up in the sprint:
- Which Platform_Class codes to add to the template. The suggestion is to add 4 codes: 54: airship; 30: Ship; 33: Self-propelled small boat; and 37: Self-propelled boat. Ships, small boats, and boats differ in size. If we don't want to distinguish between ship, small boat, and boat, we can use the code 3Z: Surface vessel - mobile platform, which is defined as "A mobile platform with propulsion operating on and restricted to the surface of a water body.".
- Whether to use the scientific name or the common name on the drop down list in the template.

All potential changes proposed on the sprint should be implemented by end of the day Friday 5/11.

**Comment by neil-ices-dk** [comment]
3 new fields in latest update: @pcrjoana to add these when @NikkiTaylorJNCC has confirmed (by 05 NOV)
- Platform Height (re-introduced)
- Duplicate Sighting Status (yes/no)
- Duplicate Sighting Number

> Which Platform_Class codes to add to the template. The suggestion is to add 4 codes: 54: airship; 30: Ship; 33: Self-propelled small boat; and 37: Self-propelled boat. Ships, small boats, and boats differ in size. If we don't want to distinguish between ship, small boat, and boat, we can use the code 3Z: Surface vessel - mobile platform, which is defined as "A mobile platform with propulsion operating on and restricted to the surface of a water body."
- use 54 and 3Z

> Whether to use the scientific name or the common name on the **drop down list** in the template.
Scientific name view in drop down;

**Comment by pcrjoana** [comment]
The data format has been finalised and it's available in [datsu](http://datsu.ices.dk/web/selRep.aspx?Dataset=149).
@cmspinto is finalising the template.

**Comment by neil-ices-dk** [comment]
template is to be published on web - macro tested by ICES but another test from JNCC would be good; (Joana will contact NikkiC about this)

**Comment by neil-ices-dk** [comment]
@pcrjoana and @NikkiTaylorJNCC and @cmspinto 
Change to data format and also data standard:
- In IDENTIFIER record change label 'NumberOfObservers' to 'NominalNumberOfObservers'
- In EFFORT record add new field 'ActualNumberOfObservers' (integer)

**Comment by NikiClear** [comment]
Noticed a slight typo in the template; cloud cover vocab list; E should be '81% to 100% cloud cover'
![image](https://user-images.githubusercontent.com/87769388/142612870-26cbf398-e9b9-4ea3-a6e6-302ac68c3541.png)
@pcrjoana @neil-ices-dk

**Comment by NikiClear** [comment]
Visibility - http://vocab.ices.dk/?ref=1708 should have 'Not recorded' option?

**Comment by NikkiTaylorJNCC** [comment]
> Visibility - http://vocab.ices.dk/?ref=1708 should have 'Not recorded' option?

Yes it should

**Comment by NikkiTaylorJNCC** [comment]
@pcrjoana the codes have been changed for platform class. They should be:
Surface vessel – mobile platform
Aeroplane
Unmanned aerial vehicle 

But instead of the last two, we have 54: airship. Can we change back to the original codes?

**Comment by pcrjoana** [comment]
@NikkiTaylorJNCC yes! Will do. I wasn't sure which code to use, so I used the one that covered all flying things. :-)

**Comment by pcrjoana** [comment]
The template has been updated.
We are still waiting for confirmation from the vocabulary management group on the new codes for Cue.

**Comment by neil-ices-dk** [comment]
> The template has been updated. We are still waiting for confirmation from the vocabulary management group on the new codes for Cue.

cue is now agreed and added to template

**Comment by pcrjoana** [comment]
The format has been updated according to the changes sent by @NikkiTaylorJNCC on 20/12. The vocabulary management group still has to approve the new vocabulary for PlatformInstance.
Right now, there's a field called DataRHContact in the format, this is to be deleted. The reason why this field hasn't been deleted is because I don't know how to delete fields without making the programme angry. The deletion will happen when a colleague teaches me how to do it.
