### ISSUE TITLE
As a Data owner/Data manager I want to restrict my data to only those who I give permission to use it ..so that I can keep track of who is using my data and refuse some uses

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#5]
original id#2

What level are the data restricted at? - 
La Rochelle Uni - restriction on data within the effort table, not the sightings etc.? 
NGO - restriction is on use (licence for use), not the level of data. Conservation, research and education.

**Comment by cmspinto** [comment]
There are only two levels of restrictions, open or closed data.
