### ISSUE TITLE
As a Data user I want to be notified when a data provider has processed my request for access to restricted data ..so that I can download the data promptly if permitted

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#50]
original id#46
depends on how this is implemented - inside with a key or outside of the system

**Comment by cmspinto** [comment]
See issue #52

**Comment by neil-ices-dk** [comment]
@kellymacleod as discussed on wrap-up call - at ICES, although this is technically possible, we feel strongly that we shouldn't provide this functionality;

**Comment by LynnHeeley** [comment]
KM SAYS #45 COVERS IT FOR RESTRICTED

**Comment by LynnHeeley** [comment]
now covered by #45 labelled duplicate and closed
