### ISSUE TITLE
As a Data user I want to ensure a quick response to a data access request ..so that I can continue with my work and the reputation of the JCDP is upheld_coordinator

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#52]
original id#48
coordinator role to ensure some response is made (track request) - copy into each request
to agree  as a project what the response time should be

Interaction outside the system....

**Comment by cmspinto** [comment]
Data users will be in direct contact with data submitter.

**Comment by neil-ices-dk** [comment]
@LynnHeeley i would reject this, the interaction depends on the data provider, and we cannot control this from within the system

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed:

Outside the system – this will be integrated into the data  policy.
--

**Comment by LynnHeeley** [comment]
the interaction depends on the data provider, and we cannot control this from within the system
