### ISSUE TITLE
As a Data user I want to be able to access species distribution at different spatial and temporal scales ..so that I complete analyses on risk and trends or monitor marine protected areas

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#54]
original id#50
raw data - not ready map maps

Wording of user story does seem product focused

Theme is around selection by location 

Close overlap with #104 
Close overlap with #163 
Some overlap with #164 
Close overlap with #162

**Comment by cmspinto** [comment]
These are views or products, needs clarification?

**Comment by LynnHeeley** [comment]
overlap with #57

**Comment by LynnHeeley** [comment]
Overlap with #51 closed
