### ISSUE TITLE
As a Data user I want to have acess to maps of species distribution ..so that I can include this (referenced, as required) in my work

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#57]
original id#53

Is this just as a visualisation (e.g. a static map), or relevant to underlying data (dynamic). 

Snapshot view of relevant sightings.

Split ticket

**Comment by cmspinto** [comment]
If this is a product from the dataset then it should be available in the download.

**Comment by LynnHeeley** [comment]
duplicate of #54, close ticket
