### ISSUE TITLE
As a Data user I want to be able to login on all pages/sections of site (including the spatial distribution page) ..so that I can save my searches/download/request permission without having to leave the page (and lose my place/filters)

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#58]
original id#54
If there is a log in, who will be data controller or data processor. Legal considerations around managing data.

**Comment by cmspinto** [comment]
It is costly to develop this, there is a user login but saving all the data and steps the user does on line is costly and the advantages are not enormous.

**Comment by neil-ices-dk** [comment]
@LynnHeeley and @kellymacleod 
the compromise solution would be what we do for some other portals. that the user can send themselves a link to their search so that they can refer/recall it.

**Comment by LynnHeeley** [comment]
@neil-ices-dk a permalink was suggested by Carlos at Steering Group Jan2020 - which is an extra step to just copying a URL. Will you provide a button/pop-up for the correct, cleaned URL?

**Comment by neil-ices-dk** [comment]
> 
> 
> @neil-ices-dk a permalink was suggested by Carlos at Steering Group Jan2020 - which is an extra step to just copying a URL. Will you provide a button/pop-up for the correct, cleaned URL?

@cmspinto care to comment?

**Comment by LynnHeeley** [comment]
@cmspinto can we have a permalink as you suggested (button to provide a shortened, tidy link to the map with the filters etc) or is this out of scope?
