### ISSUE TITLE
As a Data user I want to be able to view/change the reference layers on the spatial distribution page ..so that I can view the data in different contexts 

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#62]
original id#58

needs clarification "reference layers"   
overlap with #90 - detail here is user can switch between reference layers

**Comment by cmspinto** [comment]
Are these reference layers well established? If there is a WMS service for these layers it might be possible.

**Comment by neil-ices-dk** [comment]
@kellymacleod If it is background reference layers that are already established i.e. different management areas, then this is not a big ticket;

**Comment by LynnHeeley** [comment]
Steering Group meeting on data products decided: HELCOM areas, OSPAR areas, ICES areas, bathymetry, basemap, WGMME ICES provided advice for marine mammals, EEZs (with caveat that Neil suggested) - and these could be added later if needed/advised: Europe-wide MPAs, pressure layers

**Comment by neil-ices-dk** [comment]
thanks @LynnHeeley 
and assume we mean:
- bathymetry = one of these services from [EMD Bath](https://www.emodnet-bathymetry.eu/data-products/web-services-and-standards)
- EEZ = maritime boundaries v11 [Maritime Boundaries Geodatabase](https://marineregions.org/sources.php#marbound)

**Comment by GMDuncan** [comment]
@neil-ices-dk , if you're after a tilemap for a basemap, EMODnet Bathymetry provides fast-loading **WMTS** tilesets as well as the standard WMS. I'd recommend the "baselayer" tileset, if so.
https://tiles.emodnet-bathymetry.eu/#baselayer

Otherwise I'd suggest using "mean_atlas_land" from their WMS.

**Comment by LynnHeeley** [comment]
EEZ suggestion above approved by Kelly

**Comment by neil-ices-dk** [comment]
for the basic map inventory, reference layers we will need:
ICES ecoregions
OSPAR regions
OSPAR sub-regions

**Comment by neil-ices-dk** [comment]
see #256
