### ISSUE TITLE
As a Data user I want to be able to search for data products on the spatial distribution page by time period (year, month), species ..so that I can get to exactly the product that I need

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#65]
original id#61

**Comment by cmspinto** [comment]
These are filters for the data download

**Comment by LynnHeeley** [comment]
added specifics of date and species filtering as per Steering Group meeting discussion on #34

**Comment by LynnHeeley** [comment]
Kelly advised (29th March): time (year, month) and location - any further filtering from browse submissions table

**Comment by neil-ices-dk** [comment]
superceded by inventory discussion
