### ISSUE TITLE
As a Data/Web manager I want to provide a feedback function ..so that I respond to queries and suggestions from users

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#76]
original id#72

Clarification needed of feedback - on what? System? Data? Submission? Access? etc? 

Separate to the JCDP, or part of the wider ICES feedback system?

**Comment by cmspinto** [comment]
Develop a feedback page, example: [https://smartdots.ices.dk/Userfeedback](https://smartdots.ices.dk/Userfeedback)

**Comment by NikiClear** [comment]
Provided by the JCDP QA Feedback form. This could be closed?
