### ISSUE TITLE
As a Data/Web manager I want to ensure that only the appropriate cookies are used, these can be managed easily and a notice detailing these is available ..so that I comply with legislation about cookies

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#77]
original id#73

ICES don't use cookies so not a consideration.

**Comment by neil-ices-dk** [comment]
> original id#73
> 
> ICES don't use cookies so not a consideration.

actually we do use cookies on the main site (but not on the sub-domain cetaceans.ices.dk); we are using the Microsoft recommended settings, however the button (learn more) will be updated to say "manage preferences" to be inline with user expectations from usual practice

![image](https://user-images.githubusercontent.com/23527005/150492932-3ebe571a-fa11-40d7-911a-cb6f2204a29f.png)

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to chase Nas

**Comment by neil-ices-dk** [comment]
Nas has made a pre-deployment of this, looks fine and will deploy early September

**Comment by neil-ices-dk** [comment]
deployed now 
![image](https://user-images.githubusercontent.com/23527005/189665683-4dd08e85-6a78-411a-99f0-c69bd40f2a24.png)
