### ISSUE TITLE
As a data owner I want to indicate appropriate and non-appropriate uses of my data so that inappropriate analyses are not attributed to my data - metadata 

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#8]
original id#5
Needs to be sufficient metadata associated with the survey data so that the user has a clear understanding of the protocol and any biases to be aware of. 

it is necessary that the metadata fields cover this as much as possible

**Comment by cmspinto** [comment]
Needs clarification and discussion.

**Comment by neil-ices-dk** [comment]
counterpart to [data user story](https://github.com/ices-tools-dev/cetaceans/issues/29)
