### ISSUE TITLE
As a Data/Web manager I want to provide a well documented application programming interface (API - to access the data programmatically) ..so that I enable users to access the open/shareable data programmatically without requireing additional staff resource

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#80]
original id#76

Direct access to the data without using a GUI.

Needs a matching end-user perspective user-story to create the demand for this!

Computer to computer access (computer geeks!)

Conflicts with tracking users, if latter agreed #13

**Comment by cmspinto** [comment]
Would an R package help to facilitate the access to the WebAPI?

**Comment by neil-ices-dk** [comment]
https://cetaceans.ices.dk/webservices
