### ISSUE TITLE
As a Data/Web manager I want to ensure the process of requesting restricted data is as automated and simple as possible… so data owners can respond and download be initiated effectively where granted

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#82]
original id#78

BIG-TICKET:  High requirement from some stakeholders to have the functionality to be contacted directly by "the system" with details of the requester. However, from the hosting perspective this creates significant development and management overhead.
Needs more detail on exactly what is required and what the process would be.

**Comment by cmspinto** [comment]
Our proposal is that users are in direct contact with data providers.

**Comment by neil-ices-dk** [comment]
@kellymacleod see #45

**Comment by LynnHeeley** [comment]
covered by #45
