### ISSUE TITLE
As a Data/Web manager I want to provide a function to enable organisations/data providers to update their details (eg contact) ..so that I these can be kept up-to-date by themselves

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#84]
original id#80

Is in the bag, but not everyone can go in and update own details. Controlled internally. 

Duplicate. Will have to consider how this could work through EDMO

**Comment by cmspinto** [comment]
This is part of the EDMO codes. They can update their details at any time and the EDMO code will keep the same.
