### ISSUE TITLE
As a Data/Web manager I want to ensure that the system can ingest key data of different types (effort-related: aerial, platform based) ..so that I acoustic and sighting data can both be included

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#86]
original id#82

Clarification needed - allow potential for other data sources to contribute in future e.g. land-based. Not a short term aim, but consideration is needed for future proofing. 

Would need a separate user story for each different type of data that's being requested.

**Comment by cmspinto** [comment]
Need clarification. Is this part of the format or more than one format is needed?

**Comment by neil-ices-dk** [comment]
@LynnHeeley @kellymacleod this is out of scope for this phase of the project right?

**Comment by kellymacleod** [comment]
@neil-ices-dk yes it is.

**Comment by LynnHeeley** [comment]
Ingesting key data of different types (effort-related: aerial, platform based) is 'in the ICES bag' and defined in the data standard. The rest of the ticket - acoustic data etc is out of scope. Ticket therefore no longer required.
