### ISSUE TITLE
As a Data/Web manager I want to provide a robust and easy to use upload mechanism that provides a human-readable report ..so that I can enable data providers to upload the data themselves

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#87]
original id#83

**Comment by cmspinto** [comment]
[Here is an example of a screening report](http://datsu.ices.dk/web/ScreenResult.aspx?sessionid=11664)

**Comment by neil-ices-dk** [comment]
DATSU now screens cetacean files and produces a report http://datsu.ices.dk/web/ScreenResult.aspx?sessionid=6933
