### ISSUE TITLE
As a Data/Web manager I want to provide a download mechanism (all fields from selected area for permitted datasets) ..so that I can enable use of the data is permitted outside of the system

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#88]
original id#84

Needs clarification??
@neil-ices-dk 'in the 'CES bag' surely? overlap with #36 and #27?

**Comment by cmspinto** [comment]
Filter by choosing the data access field "open access".

**Comment by LynnHeeley** [comment]
duplicate of #36 and #27 closed
