### ISSUE TITLE
As a Data/Web manager I want to be able to include key reference layers of relevance to the project on the spatial distribution page ..so that I can provide these to users to use (eg regional areas such as Scottish waters)_needs detail

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#90]
original id#86

**Comment by cmspinto** [comment]
Is this related with Permalink: [https://wiki.openstreetmap.org/wiki/Permalink ](https://wiki.openstreetmap.org/wiki/Permalink )

**Comment by LynnHeeley** [comment]
@pcrjoana @cmspinto perhaps you could list the reference layers that you have available on your other maps already as a starter for what we will need for this.

**Comment by LynnHeeley** [comment]
duplicate of #62 closed
