### ISSUE TITLE
As a Partner I want to have the portal provide a link to my relevant webpage ..so that I market my involvement/my organisation and other related projects etc -

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#92]
original id#88

Following the definition of a partner provided for us, publication of their website may not be justified. 

Should this be in the system or through the showcase

**Comment by cmspinto** [comment]
Is this part of the project page like this: http://ices.dk/about-ICES/projects/Pages/Baltic_Data_Flows.aspx[http://ices.dk/about-ICES/projects/Pages/Baltic_Data_Flows.aspx](url)

**Comment by LynnHeeley** [comment]
showcase - outside of the ICES system, close ticket
