### ISSUE TITLE
As a Partner I want to ensure the portal is visible ..so that I ensure it is used by those who need it so it becomes an asset and selling point for scheme participation

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#95]
original id#91

This is more in line with Objectives. Needs much more detail on how the portal will be visible (e.g. SEO, promotion on ICES site, promotion on partner sites...

**Comment by cmspinto** [comment]
We think this might be part of the reason to accommodate the dataset in ICES and linking it with a group of experts

**Comment by neil-ices-dk** [comment]
@LynnHeeley this is more of an objective/mission statement, suggest to reject as user story

**Comment by LynnHeeley** [comment]
Steering Group Jan2020 agreed:
Objective, not user story.
