### ISSUE TITLE
As a Partner/Data owner I want to have profile on the webpage/system ..so that I am acknowledged

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#97]
original id#93
Following the definition of a partner provided for us, publication of their website may not be justified. 

Data owners will need to be visible 
related to #73

**Comment by cmspinto** [comment]
All users will have a user, a login and a profile. 
There won't be any dedicated webpage to the specific users.

**Comment by neil-ices-dk** [comment]
on JCDP hub
