### ISSUE TITLE
As a Partner/Data owner I want to track usage of data to enable collaboration opportunities and feedback for providers ..so that I  know how data are being used and this can be used to further demonstrate the value of the JCDP

### ISSUE THREAD

**Issue by LynnHeeley** [ices-tools-dev/cetaceans#98]
original id#94
Same theme as ticket id#17

id 17 is about tracking access. 
This is about tracking uses 
also #170

**Comment by cmspinto** [comment]
Depends what it is means with track, if it is to count the number of times data were downloaded then it is possible.

**Comment by neil-ices-dk** [comment]
see #45 as a way of the provider tracking data use (for restricted data only) and then see DOI tickets for open data

**Comment by LynnHeeley** [comment]
Cover in comms strategy once the way forward is identified

**Comment by LynnHeeley** [comment]
duplicate of #126 -dashboard. closed
